### PR TITLE
Installing Roundcube on Ubuntu 14.04

### PR DESCRIPTION
**Pull request by seanthewebber**
- Added metadata heading
- Added numbering to comply with the Linode Style Guide
- Fixed unmet PHP PEAR requirements discovered in pull request #223 (since closed)
- Improved phrasing and section descriptions
- Updated Roundcube version from 1.1.1 to 1.1.3

### CODE REVIEW

**Comment by cwlinode** [comment]
@seanthewebber Thank you for this submission. Apache needs finer configuration to work with Roundcube than our general installation guides cover. Please explicitly include such instructions in your guide so that the reader does not run into issues with file and folder paths when adding Roundcube to the stack.

**Comment by seanthewebber** [comment]
@cwlinode I looked over Roundcube's official [centos_rhel_install.sh installation script](http://trac.roundcube.net/attachment/wiki/Howto_Install/centos_rhel_install.sh) and found a set of Apache directory permissions (starting at line `31`) that didn't make it into my instructions. I just added them a moment ago.

If this is not the "finer configuration" you had in mind, please let me know.

**Comment by cwlinode** [comment]
@seanthewebber My apologies for being vague. Please include instructions to fully configure Apache's SSL virtual host for this Roundcube setup. This is a situation where it would be easier on the reader to, rather than link to our general LAMP guides, specifically:

*   apt-get install the `lamp-server^` metapackage.
*   Use a single mkdir command for the Apache public_html and logs directories.
*   Include an example vhost server block so that the reader only needs to change the domain for their own purposes.
*   Disable the default Apache vhost and enable RC's.

**Comment by seanthewebber** [comment]
@cwlinode Not a problem. Now I know what you're looking for. :) I will push a commit with those changes within a day or two.

**Comment by seanthewebber** [comment]
@cwlinode Just completed a first draft with your requested additions + changes. It's late here in Michigan, so I will spin up a **Linode 1024** and test it tomorrow (Wednesday).

**Comment by seanthewebber** [comment]
@cwlinode Completed some modifications and successfully tested it on a Linode 1024 (and took new screenshots). It's all yours! :)

**Comment by cwlinode** [comment]
@seanthewebber That looks good. Three additional points and then we can move on to the copy editing phase:

Please merge your info into our full header format, and your Prerequisites area into our Before You Begin section. See:
https://linode.com/docs/linode-writers-formatting-guide#header
https://linode.com/docs/linode-writers-formatting-guide#before-you-begin


Also, Apache isn't redirecting from port 80 to 443 because the default site hasn't been disabled. Please add this.

**Comment by seanthewebber** [comment]
@cwlinode That should do it. Let me know if anything unravels during copy-editing.

**Comment by alexfornuto** [comment]
@seanthewebber your guide has been published, but there are several merge conflicts in your branch preventing GitHub from showing this version as being merged. Your commits are still in the history under the squash commit 15854c8a0e5f11c0d7132a613734f76950c26ca9, but if you want this branch to show as merged you'll need to run `git pull --rebase origin master` and then resolve all the conflicts.

So that we can prepare for and prevent this sort of issue, perhaps you can tell us what you might have done to create conflicts across several non-related files?

Additionally, please email contribute@linode.com with your preferred method of payment, PayPal or a Linode account credit, and the associated email for your choice.

**Comment by seanthewebber** [comment]
@alexfornuto I will take care of that when I get home. I usually use the GitHub for Mac GUI client, so I'll have to mess with the CLI client to repair it.

I believe the mistake I made was writing part of this guide as the `master` branch. I didn't realize this was an issue until I went to write a second tutorial. Every new branch (e.x. `roundcube

**Comment by cwlinode** [comment]
@seanthewebber We still do not have an email for your payment details. Please contact contribute@linode.com so we can get you compensated.

**Comment by seanthewebber** [comment]
@cwlinode That's weird. I sent you an email at 10:19 AM EST yesterday via Google Inbox (Gmail):

~~~
MIME-Version: 1.0
Message-ID: <CAOYhKqY+GBDr5wx=FExE3S71WLB=L7zejKATky45K9LwLmJXaw@mail.gmail.com>
Date: Mon, 01 Feb 2016 15:19:03 +0000
Subject: [Payment] Installing Roundcube on Ubuntu 14.04 #358 
From: Sean Webber <██████████@gmail.com>
To: James Stewart <contribute@linode.com>

...

Hi Alex,

Thank you for editing and accepting my first tutorial for Linode! :) Please 
route payment to my PayPal account with the address swebber@yazzielabs.com.
~~~

I think we need to troubleshoot our email service providers. This happened in #379, too.

**Comment by cwlinode** [comment]
@seanthewebber  Payment sent.

**Comment by seanthewebber** [comment]
@cwlinode @alexfornuto Just received payment on my end. Thanks again!

How should we proceed with the email issue? You're on Google Apps for Business (according to MX records) and I am on Google Inbox. Us not receiving each others emails is concerning me.

**Comment by alexfornuto** [comment]
@seanthewebber You're the only contributor we have frequent email issues with. I suggest you review on your end.

**Pull request closed without merging**
