### PR TITLE
How to Install Odoo 10 on Ubuntu 16.04

### PR DESCRIPTION
**Pull request by damasosanoja**
Hi @alexfornuto 

Here is the draft from pull request #437 (Installing Odoo 9 update).

We're lucky Odoo 10 was released on October 03, with many enhancements under the hood. The draft includes some pictures in order to help newcomers with systemd output.

Best regards

### CODE REVIEW

**Comment by damasosanoja** [comment]
Hi, any updates on this?

**Comment by damasosanoja** [comment]
Hi @pbzona any news on this update, thanks in advance.

**Comment by pbzona** [comment]
Hi @damasosanoja. We're currently working on a publication schedule and this is certainly on our radar. I should have more information on where this fits into the schedule within the next couple weeks, and I'll be sure to let you know as soon as I can. Thanks for your patience!

**Comment by damasosanoja** [comment]
Hi @pbzona there is any update on the schedule status? Thanks in advance.

**Comment by pbzona** [comment]
Hi @damasosanoja, I apologize for the delay in getting back to you. We're undergoing quite a few changes in our publishing process, but I brought this up in a meeting earlier. We'll have a more concrete answer for you in the next few days once we have a chance to set a new schedule. Thanks for your patience.

**Comment by damasosanoja** [comment]
Hi @pbzona thanks for the information.

**Comment by pbzona** [comment]
Hi @damasosanoja,

I'm going to check out your PR today and make sure everything works as expected. Once I'm done I'll send you any suggested changes and we can start working toward getting this published (hopefully in the next week or two). Thanks again for your patience.

**Comment by damasosanoja** [comment]
Hi @pbzona 
Excellent news, I'll be looking forward to any suggestions.

**Comment by pbzona** [comment]
Hi @damasosanoja 

The guide looks great! I've made a PR to your branch here: https://github.com/damasosanoja/linode/pull/3

Please review my notes and merge, and feel free to let me know if you have concerns about any of my changes. Once that's done, we'll get a second set of eyes for a final copy edit and we should be ready to publish shortly thereafter.

**Comment by pbzona** [comment]
Thanks, @damasosanoja I'll get the next available member of my team to do one last review. Then we should be all set!

**Pull request merged**
