### PR TITLE
How to install Ghost on Ubuntu 16.04

### PR DESCRIPTION
**Pull request by BlueHatbRit**
A guide on how to install the Ghost blogging platform on Ubuntu 16.04.

Includes:
* Installing node.js and nginx
* Installing Ghost
* Basic Ghost configuration
* Keeping node running after the ssh session has been closed (using the node package, forever).

I wrote this before I saw the bounty was closed as that's not on the website. As a result I've submitted this anyway, but feel free to leave it around until you get through the backlog etc.

### CODE REVIEW

**Comment by BlueHatbRit** [comment]
Changes added by @brewn which have been merged in, just wanted to highlight them.

**Comment by BlueHatbRit** [comment]
Some more copy edits applied by @cwlinode worth highlighting.

**Comment by BlueHatbRit** [comment]
@brewn thanks for the merge, looking forward to seeing the guide up! Is there an email address I should get in touch with to move forward with the payment?

**Comment by brewn** [comment]
@BlueHatbRit It should be going up soon - if you can send your PayPal information to nbrewer@linode.com I'll make sure we get this processed today.

**Pull request merged**
