### PR TITLE
Remove duplicated word in how-to-install-postgresql-on-ubuntu-16-04.md

### PR DESCRIPTION
**Pull request by categulario**
there were two `for`

### CODE REVIEW

**Comment by GuessWhoSamFoo** [comment]
Thanks @categulario , I created a master tracker in #1418 for similar issues. Interested in tackling this?

**Comment by categulario** [comment]
How can I do it?

**Comment by GuessWhoSamFoo** [comment]
See the list in #1418 and tackle some of the ones caught by Vale

**Comment by categulario** [comment]
ohh, perfect. I'll tackle it

**Pull request merged**
