### PR TITLE
Apache SSO  with LDAP

### PR DESCRIPTION
**Pull request by alexfornuto**
This is an import from a submission given to us via email. It has not yet been reviewed for technical accuracy or edited for for proper formatting. It's purpose here is to gauge interest from the community on this subject, and solicit independent review of the contents.

### CODE REVIEW

**Comment by buhman** [comment]
:thumbsdown:

The entire idea also seems extremely specialized--I suspect article maintenance isn't worth the very small number of people this might interest. Also needs several adjustments to tone/point of view/style prior to publishing.

*Assumes an ldapd already exists, which is quite unlikely*. A series on ldap might be a good idea, and luckily upstream has [already](http://www.openldap.org/doc/admin24/quickstart.html) [done](http://www.openldap.org/doc/) all of the work for that.

This also uses mod_session--unless people have similarly specialized applications, this won't be very directly useful to people wanting to use said session in the application. If the session generated by mod_session isn't used by the application, most of the work done in the guide is fairly useless.

A more generic guide on "restricting access via (session-less) http basic authentication" is likely a better idea, applicable to a far greater number of people, has fewer prerequisites, and is easier to explain/do.

**Comment by alexfornuto** [comment]
Thanks for the input @buhman. If there are no other  thoughts on this soon I'll close it out.

**Comment by ryanwohara** [comment]
We'd be better off with LDAP guides than this.

**Comment by alexfornuto** [comment]
Thanks for your input @orzFly @buhman and @ryanwohara. In light of your comments I'm going to close this PR.

**Pull request closed without merging**
