### PR TITLE
Top Docs Video Additions

### PR DESCRIPTION
**Pull request by rsyracuse**

### CODE REVIEW

**Comment by nmelehan** [comment]
Deploy preview for *nostalgic-ptolemy-b01ab8* ready!

Built with commit decfacc5b97e9e9e28d578e95f8d13b237ef898b

https://deploy-preview-3834--nostalgic-ptolemy-b01ab8.netlify.app

**Review by Rajakavitha1 — CHANGES_REQUESTED** [review]
For the changes in the  file: docs/guides/platform/disk-images/linode-images/index.md

The location of Linode-images guide is different on netlify: https://deploy-preview-3834--nostalgic-ptolemy-b01ab8.netlify.app/docs/guides/linode-images/

**Review by Rajakavitha1 — COMMENTED** [review]
The changes for the file: https://deploy-preview-3834--nostalgic-ptolemy-b01ab8.netlify.app/docs/guides/getting-started/

On netlify it is at: https://deploy-preview-3834--nostalgic-ptolemy-b01ab8.netlify.app/docs/guides/getting-started/

**Review by Rajakavitha1 — COMMENTED** [review]
For the changes in docs/guides/platform/get-started/how-to-choose-a-linode-plan/index.md

on netlify it is located: https://deploy-preview-3834--nostalgic-ptolemy-b01ab8.netlify.app/docs/guides/how-to-choose-a-linode-plan/

**Review by Rajakavitha1 — COMMENTED** [review]
changes for the file: docs/guides/platform/marketplace/deploy-wireguard-with-marketplace-apps/index.md

on netlify: https://deploy-preview-3834--nostalgic-ptolemy-b01ab8.netlify.app/docs/guides/deploy-wireguard-with-marketplace-apps/

**Comment by Rajakavitha1** [comment]
Checked the embedded videos in all the guides and they all look good!!!

**Comment by Rajakavitha1** [comment]
@rsyracuse  Please use the YouTube short code  {{< youtube 87FJQPorviM >}} and replace '87FJQPorviM` with the id of the youtube video... this makes the md file look much cleaner.

**Comment by Rajakavitha1** [comment]
@rsyracuse  the changes look fine to me.
@andystevensname  the changes look good to me and you can approve this PR.

**Review by Rajakavitha1 — APPROVED** [review]

**Pull request merged**
