### PR TITLE
Run Minecraft in a FreeBSD Container

### PR DESCRIPTION
**Pull request by RainbowHackerHorse**
Guide to setting up Containers (jails) in FreeBSD, for running a secure Minecraft server.
Companion guide to Install FreeBSD on a Linode.

### CODE REVIEW

**Comment by Guaris** [comment]
This is really awesome!

**Comment by RainbowHackerHorse** [comment]
> not accepting guide submissions at this time
I'm aware you're not looking to pay for submissions at this time. (former employee :P )
I'm only looking to contribute to the Docs library. Whether or not I receive a bounty is irrelevant.
Mind passing this on to afornuto? Thanks :)

> no efficient way of tech testing
There's an existing guide for setting up FreeBSD on a Linode, or someone could, you know, just install it in VirtualBox.

**Comment by kcraig34** [comment]
Rainbow -

Thanks for the bounty submission. It's got merit.
The docs team has adopted a new workflow for all guides, which precludes spinning up VirtualBoxes. At this time we just don't have the bandwidth.
We're going to put this on the back burner and re-assess it later this summer.
Thanks for understanding.
FYI - AFornuto has taken employment elsewhere.

**Comment by RainbowHackerHorse** [comment]
Keith,
Mucho appreciated. 
I realize y'all are probably still a small team, sorry if my response came off a bit snarky. You know i've got nothin but <3 for ya :)
Not sure what just happened here with the Merge and Revert, I guess the merge was a mistake?

Either way, I realized yesterday that you guys have re-organized the tree since I last forked it, meaning this would belong in git/game-servers not git/applications/game-servers, so i'll go ahead and fix that, and then you guys take a look whenever you finally have time. I know you'll eventually get around to it, and like i said, I'm not exactly hurting for the bounty; I just wanted to help expand the docs library a bit. This was something I was working on before I left the company, and finally got back around to it.
(Re: alex, yeah, i forgot, hence my later edit of the comment.)

**Comment by kcraig34** [comment]
All good, Rainbow.
Thanks for the tree fix.
Will let you know when we get to it.
Keep givin' 'em hell!

**Pull request merged**
