### PR TITLE
How to build your infrastructure using Terraform and Linode

### PR DESCRIPTION
**Pull request by damasosanoja**
Hi @kcraig34 ,

I have a doubt about the custom Linode plugin that I used. The original source [btobolaski](https://github.com/btobolaski/terraform-provider-linode) has been inactive for 2 years and his original binary isn't working with current version of Terraform. I had to use proposed **go** files modifications from [displague](https://github.com/displague/terraform-provider-linode). I didn't found a displague repository with his solution implemented so in order to be able to build the plugin binary I created a repository. My doubt is: would you like to use an official Linode repository instead? 

Cordially,

Damaso Sanoja.

### CODE REVIEW

**Comment by Guaris** [comment]
Damaso, I'm trying to find a solution to this problem. For now feel free to submit a PR of your solution to:  https://github.com/linode/docs-scripts --and we will figure out a solution to this problem before the guide is published.

**Comment by damasosanoja** [comment]
Hi @Guaris,
I did the pull request. Just want to point out that is not my solution ;) all merit goes to original plugin author and modifications made by displague and others. I just put the pieces in one place in order to compile the package. I am not expert in Go but as far as I can see the problem with the original plugin is related to Linode API connection.

**Comment by sbulav** [comment]
Hi @damasosanoja . I was also looking at Linode's Terraform support.
From what I've understand:
1) btolabsky's plugin should still work with old versions of Terraform(0.5.x I suppose)
2) displague's fork of btolabsky's plugin has branch with compilied go file: [fixSSHconnInfo](https://github.com/displague/terraform-provider-linode/tree/fixSSHConnInfo/bin/terraform-provider-linode)
However, this binary is compiled for mac OS and won't start in linux.
Hadn't much time to dig into, but hopefully you'll be able to compile a working Linux version.

**Comment by damasosanoja** [comment]
Hi @sbulav,
You are right, btolabsky's plugin works on version 0.5.3, I confirmed it on Ubuntu 16.04. Fortunately displague and others found a way to make it work on the newer versions. displague's fork contains the necessary Go files, I just put the pieces together in this repo [terraform-provider-linode](https://github.com/LinodeContent/terraform-provider-linode) the compiled binary is fully working in Ubuntu 16.04 using the newest Terraform version.

**Comment by sbulav** [comment]
@damasosanoja 
Thanks, I've managed to get Terraform work with linode using your guide.
One small question - do we really have to compile provider from scratch? I've just copied compiled 
plugin "terraform-provider-linode" to a new server with freshly installed Terraform 10.7 and it works perfectly. I think copying binary should work an all x86_64 systems, so it may be worth to just put a link to a compiled plugin in your guide.

**Comment by damasosanoja** [comment]
@sbulav
 
Happy to help :)

The short answer to your question is: you're right, the compiled binary should work on Linux x86_64.

The long answer is: from a pedagogical point of view would be better to learn how to compile the provider,  because the final user could be using a different architecture. There is also a valid point related to added functionality provided by the contributors mentioned [check this pull request](https://github.com/btobolaski/terraform-provider-linode/pull/1) I had no issues resizing my test Linode or changing swap size, but btobolaski thinks different. That said, the guide could include links to MacOS, Linux, and Windows binaries but that implies regular updates to the files (when necessary). That's why I made a comment suggesting that the repository should be hosted in an official Linode branch/repo. That way they can officially endorse the binary. 

Better yet would be to be officially included in Terraform providers list, but I am not aware what is needed to achieve that.

**Comment by Jskobos** [comment]
Closed in favor of #1083.

**Pull request closed without merging**
