### PR TITLE
StartSSL with Apache on Debian or Ubuntu

### PR DESCRIPTION
**Pull request by thetechstewart**
This is an import from a submission given to us via email. It has not yet been reviewed for technical accuracy or edited for for proper formatting. It's purpose here is to gauge interest from the community on this subject, and solicit independent review of the contents.

### CODE REVIEW

**Comment by dreamerblue** [comment]
Hello, I'm the original author. I updated my article for formatting and mistakes 2 days ago via email. Please check it, thx.

**Comment by alexfornuto** [comment]
@dreamerblue We don't have your latest email. Would you like to submit your new version as it's own Pull Request from your account? This guide might help: https://www.linode.com/docs/github-guide

**Comment by dreamerblue** [comment]
OK, I will check it and try to submit a Pull Request. Thanks.

**Comment by alexfornuto** [comment]
@dreamerblue OK. I'm going to close this PR in preparation of a new one. Please reference this PR's URL in the description of your new PR so that GitHub links them.

**Pull request closed without merging**
