### PR TITLE
[NEW] Docker compose

### PR DESCRIPTION
**Pull request by Guaris**

### CODE REVIEW

**Comment by GuessWhoSamFoo** [comment]
Seems like an uppercase and lowercase version of the docs both got pushed.

**Comment by kcraig34** [comment]
@GuessWhoSamFoo -- is one preferred over the other? Do we need to eliminate one? Please advise. Thx.

**Comment by GuessWhoSamFoo** [comment]
This just means there should be two files changed rather than three.

**Comment by kcraig34** [comment]
Understood, @GuessWhoSamFoo. Thanks.

**Comment by EdwardAngert** [comment]
Looks like the all lowercase one is more cleaned up. I'll take it for a copy edit and leave it unmerged until @Guaris comes back to confirm

**Comment by Guaris** [comment]
@EdwardAngert Lowercase guide is the chosen one. It contains the DockerCE shortcode. Feel free to merge it if i'm not there, and delete the uppercase guide.  Going back on vacation now..

**Pull request merged**
