### PR TITLE
[NEW] Obtain Let's Encrypt Wildcard SSL Certificate using Certbot on CentOS 7 and Ubuntu 18.04

### PR DESCRIPTION
**Pull request by gopalraha**
Initial draft of guide on "How to Obtain a Let's Encrypt Wildcard SSL Certificate using Certbot on CentOS 7 / Ubuntu 18.04"

### CODE REVIEW

**Comment by GuessWhoSamFoo** [comment]
You okay there buddy?

**Comment by gopalraha** [comment]
@GuessWhoSamFoo 

Thanks for Reply...

Please check his guide and let me know if there any issues with this guide...

**Comment by GuessWhoSamFoo** [comment]
@gopalraha You need to follow the instructions on the readme and squash commits rather than spamming existing services.

**Comment by gopalraha** [comment]
@GuessWhoSamFoo 

Thanks for kind suggestions.

Above edit is my final edit. I have added commands for both CentOS 7 and Ubuntu 18.04.

Please abandon me if i am wrong. I don't want to spam here. 

Regards :)

**Pull request closed without merging**
