### PR TITLE
Mention commands need to be prefixed with label

### PR DESCRIPTION
**Pull request by Odaeus**
I couldn't see it mentioned anywhere in the guide that you need to write the name of the Linode before each command. I've added a brief example.

### CODE REVIEW

**Comment by FelicianoTech** [comment]
I agree that this is confusing but it looks like this specific PR may not be the exact solution. Those commands work once you choose a Linode.

From the Lish gateway, you can type the label of your Linode, which brings you to that Linode's console. If you then control-D out of that, you get to lish on the host which allows you to run those commands without any prefix.

**Comment by Odaeus** [comment]
Thanks @FelicianoTech, feel free to amend it. Though I think prefixing the label is less work than activating the console and then escaping from it as you suggest. I didn't know about that method either!

**Comment by alexfornuto** [comment]
@Odaeus @FelicianoTech I've made https://github.com/linode/docs/pull/232, which I think addresses both of your concerns, as well as some other formatting changes I felt improved the guide. What do you both think?

**Comment by FelicianoTech** [comment]
I commented in the other PR however basically, I like it.

**Comment by alexfornuto** [comment]
I merged #232 so I'm closing this PR. Thanks for bringing this to our attention @Odaeus!

**Pull request closed without merging**
