### PR TITLE
Java Development with WildFly on CentOS 7

### PR DESCRIPTION
**Pull request by thetechstewart**
This is an import from a submission given to us via email. It has not yet been reviewed for technical accuracy or edited for for proper formatting. It's purpose here is to gauge interest from the community on this subject, and solicit independent review of the contents.

### CODE REVIEW

**Comment by ellekrout** [comment]
Hello @ashraffouad! Sorry for taking so long to get back to you. I've done a tech test and have some notes:

- For the MySQL installation prereqs I would link to the [LAMP on CentOS 7](https://www.linode.com/docs/websites/lamp/lamp-server-on-centos-7) guide instead of Hosting a Website, which is for Debian/Ubuntu.

- When running the wildfly-install.sh script it hits a hiccup during the `systemctl enable $WILDFLY_SERVICE` line, and outputs the following:

> wildfly.service is not a native service, redirecting to /sbin/chkconfig.
> Executing /sbin/chkconfig wildfly on
> The unit files have no [Install] section. They are not meant to be enabled
> using systemctl.
> Possible reasons for having this kind of units are:
> 1) A unit may be statically enabled by being symlinked from another unit's
>    .wants/ or .requires/ directory.
> 2) A unit's purpose may be to act as a helper for some other unit which has
>    a requirement dependency on it.
> 3) A unit may be started when needed via activation (socket, path, timer,
>    D-Bus, udev, scripted systemctl call, ...).

- When I reach the step in which you add the Datasource it failed on both servers I tested it on with this error:

>Unexpected HTTP response: 500
>
>Request
>{
>    "address" => [
>        ("subsystem" => "datasources"),
>        ("data-source" => "MySQLDS")
>    ],
>    "operation" => "test-connection-in-pool"
>}
>
>Response
>
>Internal Server Error
>{
>    "outcome" => "failed",
>    "failure-description" => "JBAS010440: failed to invoke operation: JBAS010447: Connection is not >valid",
>    "rolled-back" => true
>}

**Comment by ellekrout** [comment]
Since a month has passed with no author response to the above concerns, closing this PR.

**Comment by ashraffouad** [comment]
Sorry @ellekrout I had a long vacation, and couldn't access server, sorry for late reply. Below reply for your comments:

1- Link for [LAMP on CentOS 7 guide](https://www.linode.com/docs/websites/lamp/lamp-server-on-centos-7) is mainly for mariadb, I'm afraid it will cause confusion if someone doesn't know mariadb is like mysql, I think we can either change as you wish or I can write the complete steps in this command, at the end they are the same commands executed but we will replace mariadb with mysql.

2- Adding WildFly as a service, I added a fork (commit: e56767abdecbc978172edd4b85486f03539f0122) to the file to fix this issue, mainly in the script /opt/wildfly-install.sh

3- I could not reproduce this error, can you please tell me exactly where it is occurring in the steps?

Sorry, I'm new to Github, and afraid if my changes/fork is not shown, please let me know if I should do more steps to show you my commit.

**Comment by alexfornuto** [comment]
@ashraffouad If you're interested in pursuing this guide and you already have a GitHub account with updates, it's probably best for you to make your own Pull Request against Linode/docs. That way your changes automatically update the PR while it's staged, and we can work more directly with you, taking advantage of inline comments as well as the rest of the community. If you reference this PR in your own, using the notation `#229`, it will create reference links on both pull requests, so we can follow the historical conversation.

**Comment by alexfornuto** [comment]
Closing so we can continue on #260.

**Pull request closed without merging**
