### PR TITLE
"Visualize Apache Web Server Logs Using the Elastic Stack" Guide Distro Variants

### PR DESCRIPTION
**Pull request by tylerjl**
Hey, documentation team! Following on from my Bitwarden guide (#3154) @nmelehan indicated that updating a few of my old guides for newer distributions would be useful, so I've adapted my "Visualize Apache Web Server Logs Using the Elastic Stack" guide for Debian 9, Debian 10, Ubuntu 18.04, and CentOS 8.

- The most noteworthy change here is that I have _also_ updated these guides for the latest version of the Elastic stack. The prior guide was using version 5.x of the various tools (Elasticsearch, Logstash, etc.) but those are fairly out-of-date now. Using the current stable releases (7.x) should be less problematic and more compatible with these later Linux distributions.
- I've developed the updates by building up changes required using the Linode distro images (`linode/debian9`, `linode/debian10`, `linode/centos8`, and `linode/ubuntu18.04`). I used `g6-standard-1` as the node type (noted in the documentation)
- I've run through the guides at _least_ once for each distro configuration to confirm the updates are correct. There don't appear to be any special cases to account for with SELinux on CentOS 8.

Let me know if you need me to make any changes. Thanks!

### CODE REVIEW

**Comment by nmelehan** [comment]
Deploy preview for *nostalgic-ptolemy-b01ab8* ready!

Built with commit 3d651f6933f505f0a3b59b94624b82c53c72e86b

https://deploy-preview-3771--nostalgic-ptolemy-b01ab8.netlify.app

**Comment by tylerjl** [comment]
Hey @nmelehan and team! I just wanted to check in on this - I saw that there were some conflicts with the latest changes in `develop` so I went ahead and resolved those.

With regards to the related changes that would likely need to be made to the variants of the guide this PR adds, should that be something I revise, or no?

**Comment by nmelehan** [comment]
@tylerjl - I'm terribly sorry, I mismanaged the merging of your Elastic Stack guides for the Linode docs repo earlier this year. I ended up fixing the conflicts in a separate PR and merged them in, but I'm not sure if we ever paid you for them. I'll send a separate email to you to follow up on invoicing/payment.

**Comment by tylerjl** [comment]
Thank you for closing the loop here @nmelehan! I'll follow up via email for next steps. I appreciate it!

**Pull request closed without merging**
