### PR TITLE
Add new guide for running a Terraria game server

### PR DESCRIPTION
**Pull request by tylerjl**
Hello again! I had such a good time with my previous guide, I thought I'd do one more for a game server, since those are noted on the list of requested topics.

This is a guide for running a [Terraria](http://terraria.org/) server (an open world genre of game similar to Minecraft.) I've tested the guide on a couple of different distros (CentOS, Debian, and Ubuntu) and it seems to work. Note that, as written in the guide, this walkthrough assumes the presence of systemd, so recent versions of those distributions are required.

I'm happy to amend this guide with any suggestions - just let me know if you'd like screenshots, more explicit steps, or additional sections. I've tried to keep this guide in-line with some of the edits made in my previous guide (section naming, indentation, etc.)

Cheers!

### CODE REVIEW

**Comment by cwlinode** [comment]
@tylerjl Thank you for your submission. It has been added to our queue for review by our internal documentation team. Before moving further though, please fix your last commit.
https://github.com/tylerjl/linode-docs/commit/6620efca996864f55952a4105fd870130e703680

**Comment by tylerjl** [comment]
Not entirely sure what tylerjl@6620efc is in reference to in terms of fixing; that was just getting the branch caught up with the latest upstream master.

**Comment by sgtbigman** [comment]
@tylerjl Yeah, not sure it's a big deal, but maybe doing a rebase against upstream/master would get rid of that extra commit and make @cwlinode happy?

On another note, thanks for this guide; I've been wanting to set up a terraria server and I'm sure this guide will be of use!

**Comment by cwlinode** [comment]
@tylerjl nm. my mistake.

**Comment by cwlinode** [comment]
@tylerjl  Going through this guide is smooth until connecting to the server to try playing the game. The Terraria service is running, as is Screen. The client connects but then is kicked off after about 5 seconds. At that point, both Screen and Terraria aren't running anymore.

Output from `journalctl -f | grep terraria` on Debian 8:

~~~
Dec 11 16:15:57 localhost systemd[1]: Started server daemon for terraria.
Dec 11 16:17:34 localhost systemd[1]: Started server daemon for terraria.
user1@localhost:~$ sudo journalctl -f | grep terraria
Dec 11 16:18:07 localhost su[12071]: pam_unix(su:session): session closed for user terraria
Dec 11 16:18:14 localhost sudo[12090]: user1 : TTY=pts/0 ; PWD=/home/user1 ; USER=root ; COMMAND=/bin/systemctl status terraria
Dec 11 16:20:43 localhost terrariad[12100]: No screen session found.
Dec 11 16:20:43 localhost systemd[1]: terraria.service: control process exited, code=exited status=1
Dec 11 16:20:43 localhost systemd[1]: Unit terraria.service entered failed state.
~~~

Output from `systemctl status terraria`:

~~~
● terraria.service - server daemon for terraria
   Loaded: loaded (/etc/systemd/system/terraria.service; enabled)
   Active: failed (Result: exit-code) since Fri 2015-12-11 16:20:43 UTC; 4min 0s ago
  Process: 12100 ExecStop=/usr/local/bin/terrariad exit (code=exited, status=1/FAILURE)
 Main PID: 12031 (code=exited, status=0/SUCCESS)
 ~~~

 Did you encounter anything like this in your own testing?

**Comment by tylerjl** [comment]
@cwlinode I've observed this when the host machine lacks sufficient resources to run the Terraria server - after I bumped up the specs of the test machine (specifically RAM) I found the server stayed up after a client connects to the server.

If that does indeed fix the problem, I can amend the guide with some troubleshooting around that error message.

**Comment by cwlinode** [comment]
@tylerjl Thanks, moving up to a Linode with 2GB of RAM solved the problem. I'll add a few lines for that being the minimum size to start with. We'll be finished with the guide on our end early next week.

**Comment by alexfornuto** [comment]
Just a reminder that you have a final draft waiting for your approval here: https://github.com/tylerjl/linode-docs/pull/5

If we don't hear back from you on Monday we'll assume approval and publish the guide. Please let us know how you would prefer payment, either by giving us your Linode account for credit or email for PayPal. If you wish, you can email this information to contribute@linode.com.

**Comment by tylerjl** [comment]
LGTM! Merged and good to go.

You can credit my account; I have the same username on my Linode account.

**Comment by cwlinode** [comment]
@tylerjl your guide is published and Linode account credited.
https://www.linode.com/docs/applications/game-servers/host-a-terraria-server-on-your-linode

**Pull request merged**
