### PR TITLE
How to Develop and Deploy your applications using Wercker

### PR DESCRIPTION
**Pull request by damasosanoja**
This is the guide draft including all images.

### CODE REVIEW

**Comment by kcraig34** [comment]
Thanks, Damaso!

We're incorporating your guide into our October editing rotation and aiming to publish by 10/31.

**Comment by GuessWhoSamFoo** [comment]
@Jskobos 

1) `sudo apt install golang-go`

2) Add to end of `.bashrc`:
```
export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
```
3) `source .bashrc`

4) Running hello.go
```
sfoo@localhost:~/go/src/github.com/golang/example/hello$ go run hello.go
Hello, Go examples!
```

**Comment by damasosanoja** [comment]
Hi @Jskobos

New commit with the "cmd: /myapp" correction, generic IP address descriptions and wercker CLI proposed workaround.

**Comment by Jskobos** [comment]
Closed in favor of #1074.

**Pull request closed without merging**
