### PR TITLE
Guide for Installing Canvas on Debian 10.

### PR DESCRIPTION
**Pull request by nasanos**
Submitting a guide for installing Canvas on Debian 10.

### CODE REVIEW

**Comment by nmelehan** [comment]
Deploy preview for *nostalgic-ptolemy-b01ab8* ready!

Built with commit 0c4044dd0f9dbe9c5d1b12dc87f24d4eec7dd6df

https://deploy-preview-4043--nostalgic-ptolemy-b01ab8.netlify.app

**Comment by Sachin-Suresh** [comment]
Hi @nasanos, Could you please help in resolving this error which occurs in the "**Install Canvas**" section _Step 7_ when I `​bundle install`.
Console suggested to `gem install bundler:2.2.16`, and `bundle _2.2.16_ install --without pulsar --path vendor/bundle` which installs the bundle. 
But, when I compile the assets - `RAILS_ENV=production bundle exec rake canvas:compile_assets`, I get the below error:

`Could not find json-2.5.1 in any of the sources`.

But Json seems to be installed when I do the following:

`gem list | grep json
json (2.5.1, default: 2.1.0)
`

**Comment by nasanos** [comment]
@Sachin-Suresh Yeah, that stage in the installation is very sensitive for whatever reason. I ran into the same issue repeatedly when I was trying to figure out the right steps to install Canvas.

Eventually, it came down to a permissions issue with the installation of Bundler, if I recall right. Can you confirm that you used `sudo` for the `sudo gem install bundler --version 2.1.4` in step **5** of the **Install Ruby** section?

Canvas is also particular on its Ruby version, so the commands the console suggested should be avoided. It looks like Canvas has had some slight changes in its installation procedure, based on its [Production Start](https://github.com/instructure/canvas-lms/wiki/Production-Start) guide. I wonder if that's why you got the suggestions, and if we can avoid them by changing the `bundle install` command to something like `bundle install --without pulsar`.

I'm diving in now to see if that's what's affecting the installation.

**Comment by nasanos** [comment]
So, I was able to get the installation to work by making the following changes to the steps in the guide. Other than these changes, I followed the steps in the guide exactly:
- In the **Install Ruby** section, step **5**: Install Bundler version **2.2.16** without `sudo`, i.e., `gem install bundler --version 2.2.16`. Possibly you still also need to install Bundler at the `sudo` level — I didn't try the installation without doing so. (And I actually ended up installing version **2.2.16** under `sudo` as well.) The two commands now used for installing Bundler would be:
```
sudo gem install bundler --version 2.1.4
gem install bundler --version 2.2.16
```
- In the **Install Canvas** section, step **7**: Add the `--without pulsar` option. Bundler is deprecating the `--without` parameter, so we should use the `bundle config` command. The new set of commands in step **7** would then be:
```
bundle config set path 'vendor/bundle'
bundle config set --local without 'pulsar'
bundle install
```

Let me know if that doesn't work for you, and we can work through it again. I will add that you may have to clean the slate before trying the installation steps again, i.e., delete the Canvas project directory and maybe even remove the Bundler version(s) you have installed.

**Comment by nasanos** [comment]
@Sachin-Suresh Yes, I think executing those commands should do it. It seems like the installation needs Bundler **2.2.16** installed for your non-root user. That worked for me.

**Comment by Sachin-Suresh** [comment]
@nasanos, so far good with the bundle installation issue. 
But when I run the `RAILS_ENV=test bundle exec rake db:initial_setup` command, I get `FATAL:  password authentication failed for user "postgres"`.

1. I altered the `postgres` users password: (I also tried with other users, for which I get the same error)
`psql -c "ALTER USER postgres WITH PASSWORD 'sach7411'"`

2. Below is my `/var/canvas/config/database.yml` file altered for both `test` and `prod`:

```
test:
  adapter: postgresql
  encoding: utf8
  database: canvas_test
  host: localhost
  username: postgres
  password: sach7411
  timeout: 5000

development:
  adapter: postgresql
  encoding: utf8
  database: canvas_development
  password: your_password
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: canvas_production
  host: localhost
  username: postgres
  password: sach7411
  timeout: 5000
```

**Comment by Sachin-Suresh** [comment]
@nasanos, still the same error. I did restart Apache.

Here is the complete error log:

> $:/var/canvas$ RAILS_ENV=test bundle exec rake db:initial_setup
> /var/canvas/vendor/bundle/ruby/2.6.0/gems/soap4r-ruby1.9-2.0.5/lib/soap/mapping/encodedregistry.rb:150: warning: constant ::Fixnum is deprecated
> /var/canvas/vendor/bundle/ruby/2.6.0/gems/soap4r-ruby1.9-2.0.5/lib/soap/mapping/encodedregistry.rb:216: warning: constant ::Fixnum is deprecated
> rake aborted!
> PG::ConnectionBad: FATAL:  password authentication failed for user "postgres"
> FATAL:  password authentication failed for user "postgres"
> /var/canvas/vendor/bundle/ruby/2.6.0/gems/pg-1.2.3/lib/pg.rb:58:in `initialize'
> /var/canvas/vendor/bundle/ruby/2.6.0/gems/pg-1.2.3/lib/pg.rb:58:in `new'
> /var/canvas/vendor/bundle/ruby/2.6.0/gems/pg-1.2.3/lib/pg.rb:58:in `connect'
> /var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/postgresql_adapter.rb:46:in `postgresql_connection'
> /var/canvas/config/application.rb:184:in `block in postgresql_connection'
> /var/canvas/config/application.rb:181:in `each'
> /var/canvas/config/application.rb:181:in `each_with_index'
> /var/canvas/config/application.rb:181:in `postgresql_connection'
> /var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
> /var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
> /var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.9/lib/switchman/active_record/connection_pool.rb:31:in `block in checkout_new_connection'
> /var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.9/lib/switchman/active_record/connection_pool.rb:25:in `checkout_new_connection'
> /var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
> /var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
> /var/canvas/config/initializers/active_record.rb:1832:in `block in acquire_connection'
> /var/canvas/config/initializers/active_record.rb:1831:in `loop'
> /var/canvas/config/initializers/active_record.rb:1831:in `acquire_connection'
> /var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
> /var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
> /var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.9/lib/switchman/active_record/connection_pool.rb:38:in `connection'
> /var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.9/lib/switchman/connection_pool_proxy.rb:61:in `connection'
> /var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
> /var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.7/lib/active_record/connection_handling.rb:221:in `retrieve_connection'
> /var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.7/lib/active_record/connection_handling.rb:189:in `connection'
> /var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.7/lib/active_record/relation/delegation.rb:92:in `connection'
> /var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.7/lib/active_record/relation/query_methods.rb:1298:in `preprocess_order_args'
> /var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.7/lib/active_record/relation/query_methods.rb:364:in `order!'
> /var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.7/lib/active_record/relation/query_methods.rb:359:in `order'
> /var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.7/lib/active_record/querying.rb:21:in `order'
> /var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.9/lib/tasks/switchman.rake:34:in `scope'
> /var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.9/lib/tasks/switchman.rake:71:in `block (3 levels) in shardify_task'
> /var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.9/lib/switchman/database_server.rb:109:in `unguard'
> /var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.9/lib/tasks/switchman.rake:68:in `block (2 levels) in shardify_task'
> /var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.9/lib/switchman/guard_rail.rb:24:in `activate'
> /var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-inst-jobs-3.1.2/lib/switchman_inst_jobs/guard_rail.rb:8:in `activate'
> /var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.9/lib/tasks/switchman.rake:67:in `block in shardify_task'
> /var/canvas/lib/tasks/db_load_data.rake:227:in `block (2 levels) in <top (required)>'
> /var/canvas/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
> Tasks: TOP => db:migrate:predeploy
> (See full trace by running task with --trace)

**Comment by nasanos** [comment]
@Sachin-Suresh Hm, that's strange. It's normal that the database doesn't have any tables yet — the `db:initial_setup` command is supposed to create and populate them, I believe. But I don't get why your credentials aren't working.

You could try creating and using a specific `canvas` Postgres user, like in steps **3** and **4** of the **Install PostgreSQL** section. I don't know why that would make a difference, but maybe.

Here are the relevant two commands:
```
 sudo -u postgres createuser canvas --no-createdb --no-superuser --no-createrole --pwprompt
 sudo -u postgres createdb canvas_production --owner=canvas
```

Then, you would need to update `/var/canvas/config/database.yml` to something like:
```
test:
  adapter: postgresql
  encoding: utf8
  database: canvas_production
  host: localhost
  username: canvas
  password: sach7411
  timeout: 5000

development:
  adapter: postgresql
  encoding: utf8
  database: canvas_development
  password: your_password
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: canvas_production
  host: localhost
  username: canvas
  password: sach7411
  timeout: 5000
```

**Comment by Sachin-Suresh** [comment]
@nasanos, I could finally get it with a new user. 
Had to use: `ALTER DATABASE canvas_production OWNER TO testuser;`.

Now, when I go to my server's domain in the browser I get the `Index of /` contents displayed.

What might be the issue in the `canvas.config`?

**Comment by nasanos** [comment]
@Sachin-Suresh Yeah, you should change the `PassengerDefaultUser` in the `passenger.conf` file. The username should match the Linux user you used to set up Canvas. You may also need to add the `PassengerStartTimeout 180` line in there. I couldn't get Canvas to start up without it.

The only other thing I can think of is ensuring that the domain name in the `domain.yml` file and the `canvas.conf` files match. It looks like they do based on your messages, but maybe make sure one of them doesn't have a terminating `/`?

For reference, here is my `canvas.conf`. I've redacted my email from `ServerAdmin`, but it's the same address I used when I was setting up the Canvas admin user:
```
<VirtualHost *:80>
  ServerName debian-test.nathanielps.com
  ServerAlias debian-test.nathanielps.com
  ServerAdmin example@example.com
  DocumentRoot /var/canvas/public
  RewriteEngine On
  RewriteCond %{HTTP:X-Forwarded-Proto} !=https
  RewriteCond %{REQUEST_URI} !^/health_check
  RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [L]
  ErrorLog /var/log/apache2/canvas_errors.log
  LogLevel warn
  CustomLog /var/log/apache2/canvas_access.log combined
  SetEnv RAILS_ENV production
  <Directory /var/canvas/public>
    Allow from all
    Options -MultiViews
  </Directory>
</VirtualHost>
<VirtualHost *:443>
  ServerName debian-test.nathanielps.com
  ServerAlias debian-test.nathanielps.com
  ServerAdmin nathanielps@gmail.com
  DocumentRoot /var/canvas/public
  ErrorLog /var/log/apache2/canvas_errors.log
  LogLevel warn
  CustomLog /var/log/apache2/canvas_ssl_access.log combined
  SSLEngine on
  BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown
  SSLCertificateFile /etc/ssl/certs/ssl-cert-snakeoil.pem
  SSLCertificateKeyFile /etc/ssl/private/ssl-cert-snakeoil.key
  SetEnv RAILS_ENV production
  <Directory /var/canvas/public>
    Options All
    AllowOverride All
    Require all granted
  </Directory>
</VirtualHost>
```

**Comment by Sachin-Suresh** [comment]
@nasanos I still get the `/index of` page.

I am pasting all my config files for reference. If you could point out where I am wrong!

**`canvas.config`:**

```
<VirtualHost *:80>
  ServerName i2261-220.linodedocsdomain2.xyz

  ServerAdmin admin@example.com
  DocumentRoot /var/canvas/public
  RewriteEngine On
  RewriteCond %{HTTP:X-Forwarded-Proto} !=https
  RewriteCond %{REQUEST_URI} !^/health_check
  RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [L]
  ErrorLog /var/log/apache2/canvas_errors.log
  LogLevel warn
  CustomLog /var/log/apache2/canvas_access.log combined
  SetEnv RAILS_ENV production
  <Directory /var/canvas/public>
    Allow from all
    Options -MultiViews
  </Directory>
</VirtualHost>
<VirtualHost *:443>
  ServerName i2261-220.linodedocsdomain2.xyz

  ServerAdmin admin@example.com
  DocumentRoot /var/canvas/public
  ErrorLog /var/log/apache2/canvas_errors.log
  LogLevel warn
  CustomLog /var/log/apache2/canvas_ssl_access.log combined
  SSLEngine on
  BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown
  SSLCertificateFile /etc/ssl/certs/ssl-cert-snakeoil.pem
  SSLCertificateKeyFile /etc/ssl/private/ssl-cert-snakeoil.key
  SetEnv RAILS_ENV production
  <Directory /var/canvas/public>
    Options All
    AllowOverride All
    Require all granted
  </Directory>
</VirtualHost>
```

**`passenger.config`:**

```
<IfModule mod_passenger.c>
  PassengerRoot /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini
  PassengerDefaultRuby /usr/bin/passenger_free_ruby
  PassengerDefaultUser testuser
  PassengerStartTimeout 180
</IfModule>
```

Not sure if a change is required in **`000-default.config`** (Have removed the default Apache site configuration)
```
<VirtualHost *:80>
        # The ServerName directive sets the request scheme, hostname and port that
        # the server uses to identify itself. This is used when creating
        # redirection URLs. In the context of virtual hosts, the ServerName
        # specifies what hostname must appear in the request's Host: header to
        # match this virtual host. For the default virtual host (this file) this
        # value is not decisive as it is used as a last resort host regardless.
        # However, you must set it for any further virtual host explicitly.
        #ServerName www.example.com

        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        # For most configuration files from conf-available/, which are
        # enabled or disabled at a global level, it is possible to
        # include a line for only one particular virtual host. For example the
        # following line enables the CGI configuration for this host only
        # after it has been globally disabled with "a2disconf".
        #Include conf-available/serve-cgi-bin.conf
</VirtualHost>

```

**`database.yml`**

```
# do not create a queue: section for your test environment
test:
  adapter: postgresql
  encoding: utf8
  database: canvas_production
  host: localhost
  username: testuser
  password: sach7411
  timeout: 5000

development:
  adapter: postgresql
  encoding: utf8
  database: canvas_development
  password: your_password
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: canvas_production
  host: localhost
  username: testuser
  password: sach7411
  timeout: 5000
```

**`domain.yml`**

```
test:
  domain: localhost

development:
  domain: "localhost:3000"
  # If you want to set up SSL and a separate files domain, use the following and set up puma-dev from github.com/puma/puma-dev
  # domain: "canvas-lms.test" # for puma-dev
  # files_domain: "canvas-lms.files" # for puma-dev
  # ssl: true

production:
  domain: "i2261-220.linodedocsdomain2.xyz"
  # whether this instance of canvas is served over ssl (https) or not
  # defaults to true for production, false for test/development
  ssl: true
  # files_domain: "canvasfiles.example.com"
```

After updating all files, I did:

- sudo /etc/init.d/apache2 restart
- sudo /etc/init.d/canvas_init start

This is what my canvas error log says:

```
[Thu May 20 02:06:29.811644 2021] [ssl:warn] [pid 18985:tid 140061643856832] AH01909: i2261-220.linodedocsdomain2.xyz:443:0 server certificate does NOT include an ID which matches the server name
```

I had modified the SSL as per the guide in the "Set Up an SSL Certificate" section. Even then, I used to get the same error.

**Comment by nasanos** [comment]
@Sachin-Suresh Okay, the `/index of` seems to make a little more sense to me with the error you're getting when trying to enable the Passenger Apache module. It seems like, because Passenger isn't working/enabled, Apache is trying to serve the Canvas content directly, which doesn't work.

I do have a `passenger.load` file. Here's what is inside of it:
```
### Begin automatically installed Phusion Passenger load snippet ###
LoadModule passenger_module /usr/lib/apache2/modules/mod_passenger.so
### End automatically installed Phusion Passenger load snippet ###
```

If that doesn't do it for you, you could go back through the commands in the **Install Apache** section to make sure of or even retry the Passenger and Passenger Apache module installation. You can also use the following commands to verify that Passenger and the Passenger Apache module are installed:
```
passenger -v
sudo apache2ctl -M
```

Otherwise, you configuration files look fine to me. The `000-default.config` doesn't need to be modified; just make sure you have removed or unlinked Apache's default site configuration, as in:
```
sudo unlink /etc/apache2/sites-enabled/000-default.conf
```

**Comment by Sachin-Suresh** [comment]
@nasanos In the 3rd step in the **"Install Apache"** section, when I execute - `sudo apt install apache2 apache2-dev passenger libapache2-mod-passenger`, I get the below error:

linodeuser@li2262-60:/var/canvas$ sudo apt install apache2 apache2-dev passenger libapache2-mod-passenger
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

```
The following packages have unmet dependencies:
 libapache2-mod-passenger : Depends: libgcc-s1 (>= 3.0) but it is not installable
                            Depends: libstdc++6 (>= 9) but 8.4.0-1ubuntu1~18.04 is to be installed
 passenger : Depends: libc6 (>= 2.28) but 2.27-3ubuntu1.4 is to be installed
             Depends: libcrypt1 (>= 1:4.1.0) but it is not installable
             Depends: libgcc-s1 (>= 3.0) but it is not installable
             Recommends: passenger-doc (= 1:6.0.8-1~focal1) but it is not going to be installed
             Recommends: passenger-dev (= 1:6.0.8-1~focal1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by Sachin-Suresh** [comment]
@nasanos - I have got everything installed and in place, I am able to see the passenger version. 

Also, when I load my site in the browser, I see the URL now redirects to - `https://li2262-60.testsitetestsite.club/login/canvas` but with an empty page.

When I checked the browser (in mozilla) console, it says - 

```
Some cookies are misusing the recommended “SameSite“ attribute
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.
```

Is this some kind of CSRF issue? Any idea where this can be changed?

**Comment by nasanos** [comment]
@Sachin-Suresh This stage with the Canvas install can be a little tricky to debug, as I recall. I remember having a similar issue to the one you're having in Firefox when I first wrote the guide, and I think it related either to a permissions issue or an issue with the version of some Ruby component.

The best way to get an idea is to start looking at the logs. You can check the usual Apache logs, but more likely the most helpful stuff will be in one of these logs:
- `/var/canvas/log/production.log`
- `/var/log/apache2`
    - `canvas_access.log`
    - `canvas_errors.log`
    - `canvas_ssl_access.log`

Based on what you added about Chrome, you also might try increasing the `PassengerStartTimeout`, restarting Apache, and trying to visit the page again.

**Review by andystevensname — APPROVED** [review]

**Comment by geet-h17** [comment]
is canvas-lms supported on debian 11?

**Comment by nasanos** [comment]
> is canvas-lms supported on debian 11?

Conceivably, you should be able to run Canvas on Debian 11. For this guide our testing was on Debian 10, but for a parallel guide we used Ubuntu 20.04, which to my understanding is built on Debian 11. Similarly, the [official documentation](https://github.com/instructure/canvas-lms/wiki/Production-Start#prerequisites) mentions testing on Ubuntu 20.04.

So probably you should be able to run Canvas using the same or similar steps as in this Debian 10 guide. But keep in mind that we haven't specifically tested the installation on Debian 11, and the official documentation only covers steps for Ubuntu 20.04, so I can't say whether or not some configuration differences or difficulties may come up.

**Comment by geet-h17** [comment]
Summary:
while running RAILS_ENV=production bundle exec rake canvas:compile_assets it is giving a huge error list mostly consisting of line like
@instructure/filter-console-messages has no build:canvas script, skipping missing
@canvas/backbone-input-view has no build:canvas script, skipping missing
@canvas/backbone-input-filter-view has no build:canvas script, skipping missing
@instructure/canvas-media/courses_controller.rb.................
$ yarn installTranslations && yarn run build:es && yarn run build:cjs
@instructure/grading-utils
$ yarn build
@instructure/k5uploader
$ babel -d es src & babel --config-file=./babel.config.cjs.js -d lib src
@canvas/engine
$ yarn run check && yarn run lint
@instructure/canvas-rcers/courses_controller.rb..................
$ scripts/build-canvas
| rm: cannot remove 'es/bridge/tests/bridge.test.d.ts': Permission denied
| rm: cannot remove 'es/bridge/Bridge.d.ts': Permission denied
| rm: cannot remove 'es/bridge/index.d.ts': Permission denied
| rm: cannot remove 'es/bridge/index.js': Permission denied
| rm: cannot remove 'es/bridge/Bridge.js': Permission denied
| rm: cannot remove 'es/canvasFileBrowser/FileBrowser.js': Permission denied
| rm: cannot remove 'es/canvasFileBrowser/tests/filesHelpers.d.ts': Permission denied
| rm: cannot remove 'es/canvasFileBrowser/tests/FileBrowser.test.d.ts': Permission denied
| rm: cannot remove 'es/canvasFileBrowser/FileBrowser.d.ts': Permission denied
| rm: cannot remove 'es/canvasFileBrowser/en-US.d.ts': Permission denied
| rm: cannot remove 'es/canvasFileBrowser/en-US.js': Permission denied
| rm: cannot remove 'es/common/fileUrl.js': Permission denied
| rm: cannot remove 'es/common/scroll.d.ts': Permission denied
| rm: cannot remove 'es/common/browser.js': Permission denied
| rm: cannot remove 'es/common/getCookie.d.ts': Permission denied`

Steps to reproduce:
Clone the repo and follow the guide for ubuntu 20(with updated ruby )
reach till the RAILS_ENV=production bundle exec rake canvas:compile_assets
run it
Expected behavior:
Successfully completing the process

Actual behavior:
rm cannot remove errors

Additional notes:
i have git checkout on prod .
all these are rm files are supposedly on scripts/build-canvas

**Comment by nasanos** [comment]
@geet-h17 What distribution is that on? Like I mentioned, this tutorial only has Debian 10 in its scope; anything beyond that, and beyond the content of the tutorial generally, is really outside of the PR's scope. At that point, you should probably be talking with the Canvas team and/or the Canvas community to work through installation issues.

**Pull request merged**
