### PR TITLE
Neovim basics

### PR DESCRIPTION
**Pull request by gacanepa**
This is an introductory guide to NeoVim, a drop-in replacement for the vim text editor
nvim-completion-manager

### CODE REVIEW

**Comment by EdwardAngert** [comment]
[and we're live!](https://linode.com/docs/tools-reference/how-to-install-neovim-and-plugins-with-vim-plug)

Thanks @gacanepa!

**Comment by gacanepa** [comment]
Thank YOU @EdwardAngert and @kcraig34!

**Comment by gacanepa** [comment]
@EdwardAngert Just noticed my Twitter account is not correctly linked in the guide. Would you be as kind as to take a look?
twitter

**Comment by EdwardAngert** [comment]
nice catch, @gacanepa - fixed version is [live on the site now](https://linode.com/docs/tools-reference/how-to-install-neovim-and-plugins-with-vim-plug)

Enjoy your day

**Pull request merged**
