### PR TITLE
Install Odoo 13 Stack on Ubuntu 18.04 initial draft

### PR DESCRIPTION
**Pull request by damasosanoja**
@nmelehan 

Nathan as discussed, here is the first draft, an update to Odoo guide for Ubuntu 18.04

I made some changes to simplify the guide (thinking on Kubernetes and Docker versions):

- No PostgreSQL replication. Odoo web application and PostgreSQL database are on separate Linodes but without db replication. There is a link to the old guide for readers interested in implementing PostgreSQL replication.
- No archiving for PostgreSQL
- No custom logs for Odoo. Since this version is more mature there is no need to keep a separate log, systemd journal is used instead.

### CODE REVIEW

**Comment by nmelehan** [comment]
Deploy preview for *nostalgic-ptolemy-b01ab8* ready!

Built with commit 96f6aa1e8c6f3e6466f596e7ea36e0264aca7946

https://deploy-preview-3176--nostalgic-ptolemy-b01ab8.netlify.com

**Comment by damasosanoja** [comment]
@nmelehan Glad to hear you are good :) changes done

**Comment by hzoppetti** [comment]
Hi @damasosanoja,
Hello! I'm working with Nate at Linode for some editing. Can you please give me permissions to push to your branch? I have some edits for this.

I also have some questions:

As written, I have no problems getting the server deployment up and running with the /tmp virtualenv. However, when rebooting to test if the server service will come back, this does not work because the tmp directory is not there? and the error: directory /tmp/odoo-env/bin/python3 cannot be found

So, I tried again making a different directory as you suggested, I called this /py-odoo and gave user odoo ownership of this. However, when starting the service initially, I get an error that: 
ModuleNotFoundError: No module named 'PyPDF2'

I tried to install this, even though I do see it is installed and listed in the requirements.txt... And when trying to install it, it says, of course, that it's not needed, it's already installed.

Any ideas?

Thanks!

**Comment by damasosanoja** [comment]
Hi @hzoppetti 

I just sent you the collaborator invitation. 

Regarding the issue you mention, in all honesty, I don't remember having that problem :P Please let me check on my side, I'll create the Linode again :) 

Happy weekend @hzoppetti @nmelehan

**Comment by hzoppetti** [comment]
Sorry about that mass commit >.< I should have force pushed and forgot. I rebased and this ended up getting a ton of new things from develop branch.

**Comment by hzoppetti** [comment]
Closed in favor of this guide: https://github.com/linode/docs/pull/3649

**Comment by damasosanoja** [comment]
Hello @hzoppetti @nmelehan hope you had a great weekend!

I found the issue, the virtual environment gets deleted after rebooting the Linode. Probably not a good idea saving it to /tmp?

Creating it in /home seems to solve the problem. I'll fix the article and let you know when ready :)

**Pull request closed without merging**
