### PR TITLE
Docker in Production

### PR DESCRIPTION
**Pull request by bobstrecansky**

### CODE REVIEW

**Comment by kcraig34** [comment]
Thanks, @bobstrecansky. We've pulled it into our iteration. Still scheduled for November publishing.

**Comment by bobstrecansky** [comment]
@kcraig34 - still a Work In Progress.  I'll rebase and notify you when it's completed.  Still very on track for November publishing.

**Comment by kcraig34** [comment]
Thanks for the update, @bobstrecansky. We'll await word from you before processing. No problemo!

**Comment by bobstrecansky** [comment]
@kcraig34 - This is ready for review!

**Comment by kcraig34** [comment]
Thanks, Bob. Putting it into the editing pipeline.
If necessary, one of our guys will let you know its progress over the next week or so.
Much obliged.

**Comment by cwlinode** [comment]
@bobstrecansky Thank you for submitting this pull request. However, we're looking for a start to finish tutorial for accomplishing something. This would be a great blog post on Docker but it doesn't have the depth that we're looking for and a lot of this information is contained in our other Docker guides.

The topic of Docker used at the business or enterprise level may be better suited by focusing deeper on a single use case and walking the reader through building that out, rather than aiming for breadth with a generic feature list which is easily available in Docker's documentation.

**Comment by bobstrecansky** [comment]
@cwlinode, I’m happy to add additional colour to this article. I wasn’t driven in any direction for my initial draft. What would you like for this guide to accomplish start to finish?

**Comment by GuessWhoSamFoo** [comment]
Perhaps something like managing the lifecycle of a microservice doing something trivial in Flask. Probably can pull nginx and Postgres images. e.g Introduce the idea of why someone might/or might not want to put a database in Docker. Lead into the concept of a Dockerfile then finally linking containers. Then how container orchestration via Docker Compose can manage the whole process rather than starting each container individually.

In essence, take the "Container Commandments" and illustrate those points in context rather than stating them. Feel free to ping if you have any questions

**Comment by GuessWhoSamFoo** [comment]
@bobstrecansky Any updates?

**Comment by bobstrecansky** [comment]
@GuessWhoSamFoo - I haven't been able to get to it with other competing priorities.  I can revisit this next week.

**Comment by bobstrecansky** [comment]
@GuessWhoSamFoo - I've written a new guide here: https://github.com/linode/docs/pull/1338

**Comment by kcraig34** [comment]
Thanks for the additional effort, @bobstrecansky --
The team will get back to you soon!
Happy holidays...

**Comment by GuessWhoSamFoo** [comment]
Closed in favor of #1338

**Pull request closed without merging**
