### PR TITLE
[Update] Linode Managed

### PR DESCRIPTION
**Pull request by rsyracuse**
UI Updates

### CODE REVIEW

**Comment by nmelehan** [comment]
Deploy preview for *nostalgic-ptolemy-b01ab8* ready!

Built with commit ecef5dbaa46ca5afddcd5f7293b05a7822692e8c

https://deploy-preview-3977--nostalgic-ptolemy-b01ab8.netlify.app

**Review by Rajakavitha1 — CHANGES_REQUESTED** [review]
The short guide listed under the services section needs to be updated. Adding a New Service the image does not appear
Screenshot 2021-02-05 at 11 52 30 AM

**Comment by Rajakavitha1** [comment]
@rsyracuse  could you please make the changes requested because I am not able to push the image to your branch.

**Comment by leslitagordita** [comment]
@rsyracuse I cherry-picked the commits directly into release-v1.19.0. Closing this one in preference for that.

**Pull request closed without merging**
