### PR TITLE
[New] Self hosted password management with bitwarden_rs

### PR DESCRIPTION
**Pull request by tylerjl**
Hi, Linode docs team!

It's been a while since my last guide, but here's the previously-discussed Bitwarden guide. As noted in the introduction to this guide, this tutorial is concerned with deploying `bitwarden_rs`, which is a smaller service suited for individual deployments on private servers, but provides API comptability with Bitwarden mobile applications, desktop applications, and browser extensions. The guide covers deployment (including TLS), backups, account creation, and configuration for client programs.

I've run through the steps a few times with an Ubuntu 18.04 Linode without issues, but if there are any concerns here (either with replication of steps, additional needed sections, et cetera) please let me know. :+1: 

I've managed to run the vale CI tests successfully but ran into problems running the blueberry and 404 tests; I'll watch CI and resolve those if they arise.

### CODE REVIEW

**Comment by nmelehan** [comment]
Deploy preview for *nostalgic-ptolemy-b01ab8* ready!

Built with commit 320aa3603fb05b0b5b119207d5a1f7e96c3df5d9

https://deploy-preview-3154--nostalgic-ptolemy-b01ab8.netlify.com

**Comment by nmelehan** [comment]
Deploy preview for *nostalgic-ptolemy-b01ab8* ready!

Built with commit f1b7a46c2b76e187d16f4f5e9505c04ae6995b3e

https://deploy-preview-3154--nostalgic-ptolemy-b01ab8.netlify.com

**Comment by tylerjl** [comment]
Fixed CI tests. As one additional note, I nested the guide directly underneath `security/` as I didn't find a category fit for this elsewhere, I'm not overly attached in any way about where this is placed if there's a better spot for it in the markdown hierarchy.

**Comment by Rajakavitha1** [comment]
Hi @tylerjl !!! Thank you for this contribution. I validated the steps on ubuntu 20.04 and works fine. However, when i tried to access  using FireFox there was an error. It worked fine on safari, chrome, and edge.
Screenshot 2020-10-06 at 6 22 44 PM
Screenshot 2020-10-06 at 6 24 25 PM

**Comment by tylerjl** [comment]
Hi @Rajakavitha1, thank you for running through the guide! 

I believe the problem here is that some of the browsers might have defaulted to navigating to the domain `www.rajie.wiki` instead of `rajie.wiki` - based upon the fact that the correct page has `rajie.wiki` in the address bar but Firefox is at `www.rajie.wiki`, I would assume that the Caddy configuration file has `rajie.wiki` listed as the domain to serve and acquire a certificate for, is that correct?

If that is the case, access to Bitwarden needs to happen consistently at the domain configured in the guide to avoid SSL errors without any extra subdomains (as might be happening with `www.rajie.wiki`).

**If** that is indeed the problem, should I add a note calling out that fact to help remind individuals when others follow the guide? If that isn't the issue, we might need to debug elsewhere.

**Comment by Rajakavitha1** [comment]
> Hi @Rajakavitha1, thank you for running through the guide!
> 
> I believe the problem here is that some of the browsers might have defaulted to navigating to the domain `www.rajie.wiki` instead of `rajie.wiki` - based upon the fact that the correct page has `rajie.wiki` in the address bar but Firefox is at `www.rajie.wiki`, I would assume that the Caddy configuration file has `rajie.wiki` listed as the domain to serve and acquire a certificate for, is that correct?

Yes!!! That is correct.
> 
> If that is the case, access to Bitwarden needs to happen consistently at the domain configured in the guide to avoid SSL errors without any extra subdomains (as might be happening with `www.rajie.wiki`).
> 
> **If** that is indeed the problem, should I add a note calling out that fact to help remind individuals when others follow the guide? If that isn't the issue, we might need to debug elsewhere.

I think a note calling out the fact might help.

**Comment by tylerjl** [comment]
Sounds good @Rajakavitha1! 769d812 should help clarify that. I've also merged in the latest `master` changes to avoid merge conflicts.

Let me know if you find anything else that I should include or revise.

**Comment by Rajakavitha1** [comment]
> Sounds good @Rajakavitha1! [769d812](https://github.com/linode/docs/commit/769d8120237c36e7f5bad477b59f6b2130b59638) should help clarify that. I've also merged in the latest `master` changes to avoid merge conflicts.
> 
> Let me know if you find anything else that I should include or revise.

Thank you!!!

**Pull request closed without merging**
