### PR TITLE
[update]Added full path to each command and remove unwanted commands like cd

### PR DESCRIPTION
**Pull request by gopalraha**
Added full path to each command and remove unwanted commands like cd also added wget instead of curl command.

### CODE REVIEW

**Comment by nmelehan** [comment]
Deploy preview for *nostalgic-ptolemy-b01ab8* ready!

Built with commit 6ea259bfa4a909868e34ff9201cd0942b986cb2d

https://deploy-preview-2814--nostalgic-ptolemy-b01ab8.netlify.com

**Comment by Rajakavitha1** [comment]
Thanks for the PR @gopalraha !!! We appreciate your valuable contributions in making Linode Docs better.

**Comment by Rajakavitha1** [comment]
Hi @gopalraha !!! 
Linode appreciates your contributions in fixing the doc issues that needed help.
Could you please drop an email to aguarisma@linode.com with the details of the issues and the PRs that have addressed the issue after the PR's are merged successfully.... a surprise awaits you.

**Comment by gopalraha** [comment]
Thank you for recognizing my contribution to the Linode team. I really appreciate your encouragement and kind words.

**Pull request merged**
