### PR TITLE
Add guide for CoreOS

### PR DESCRIPTION
**Pull request by muhmuhten**

### CODE REVIEW

**Comment by cwlinode** [comment]
@muhmuhten Everything is looking good with the tech test. Can you please fix the formatting so paragraphs don't break to new lines after about 70 or so characters.

**Comment by muhmuhten** [comment]
Done, and rebased to current master head.

**Comment by cwlinode** [comment]
@muhmuhten Have hit a snag. CoreOS installs fine, but I can't log in. SSH to the Linode's IP address, and to `core@IPaddr`, want a password but according to [this](https://github.com/coreos/docs/issues/10), the default core user doesn't have one. Even when I specify a user and password hash in cloud-config.yml, the password I hashed does not work.

Config file used (w/o forcing a user):
`cloud-config.yml` file used:
~~~
#cloud-config

ssh-authorized-keys:
	  - "ssh-rsa ..."
~~~

Had you encountered anything like this?

**Comment by muhmuhten** [comment]
No authorized_keys is being generated. The key in CoreOS cloud-config [is `ssh_authorized_keys`, as documented on the page linked](https://coreos.com/os/docs/latest/cloud-config.html) rather than the more common implementation's `ssh-authorized-keys`.

**Comment by cwlinode** [comment]
@muhmuhten Thanks for that, but I'm still being asked for a password.

cloud-config.yml file:
~~~
#cloud-config

ssh_authorized_keys:
      - "ssh-rsa ..."
~~~

Taken from the cloud config file [link](https://coreos.com/os/docs/latest/cloud-config.html#ssh_authorized_keys) but using my public rsa key.

**Comment by muhmuhten** [comment]
I'm not reproducing the issue. I'm successfully logging in via ssh with this cloud-config.yml, which is not substantially different:

    #cloud-config
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE2ZHAJlT0gLVh90SiQUTEDOGyG9iSBvJcd/v43Ip0by en@koizumi

What is the output if you `ssh -v`? Can you check that the cloud-config file is being successfully passed in to coreos-install? If you boot into recovery mode, it should be found in /dev/sda9 at /var/lib/coreos-install/user_data

**Comment by cwlinode** [comment]
Hmm, got it figured out. The problem was my SSH key not working. Made a new keypair and was able to log in just fine. The guide is in the copy editing phase now so should be ready for publishing shortly.

**Comment by kcraig34** [comment]
@muhmuhten - Please disregard the immediately preceding pull request. Another will follow shortly. Thanks.

**Pull request merged**
