### PR TITLE
Initial draft of Apache on AlmaLinux guide

### PR DESCRIPTION
**Pull request by JeffreyNovotny**

### CODE REVIEW

**Comment by nmelehan** [comment]
:heavy_check_mark: Deploy Preview for *nostalgic-ptolemy-b01ab8* ready!


:hammer: Explore the source changes: 255c149eda12ae92c21bd678199307a2659cf3ad

:mag: Inspect the deploy log: [https://app.netlify.com/sites/nostalgic-ptolemy-b01ab8/deploys/60bddfd1f021880008a6db8f](https://app.netlify.com/sites/nostalgic-ptolemy-b01ab8/deploys/60bddfd1f021880008a6db8f?utm_source=github&utm_campaign=bot_dl)

:sunglasses: Browse the preview: [https://deploy-preview-4392--nostalgic-ptolemy-b01ab8.netlify.app](https://deploy-preview-4392--nostalgic-ptolemy-b01ab8.netlify.app?utm_source=github&utm_campaign=bot_dp)

**Comment by Sachin-Suresh** [comment]
Hi @JeffreyNovotny, In the `Test the Apache Web Server` section, is `cp index.html /var/www/html` to be executed from `home` folder?

When I execute in home folder, I get : `cp: cannot stat 'index.html': No such file or directory`

**Comment by JeffreyNovotny** [comment]
Oh, that's just supposed to represent the index file for the user's web domain. Unless you've already created an .html file by that name, you probably won't have a file by that name in your home directory.

I'm assuming here that the user is going to already have or intends to create a web page. In other words, the user should copy their index.html file (wherever it is) to /var/www/html. The command line is just an example of them doing that. But I see that I should have specified it like this instead (making it more clear that it should be copied from wherever it is currently located to /var/www/html).

cp <path-to-home-page>/index.html /var/www/html

We could also reword the explanation differently to make this more clear. We could say. "Copy the home page for your website, if it exists, into the `/var/www/html` directory. Otherwise, create a simple `index.html` file in that directory to represent the eventual home page." Or something like that. If it is confusing to you, it will probably be confusing to others, so it should be reworked.

**Comment by Sachin-Suresh** [comment]
> Oh, that's just supposed to represent the index file for the user's web domain. Unless you've already created an .html file by that name, you probably won't have a file by that name in your home directory.
> 
> I'm assuming here that the user is going to already have or intends to create a web page. In other words, the user should copy their index.html file (wherever it is) to /var/www/html. The command line is just an example of them doing that. But I see that I should have specified it like this instead (making it more clear that it should be copied from wherever it is currently located to /var/www/html).
> 
> cp path-to-home-page/index.html /var/www/html
> 
> We could also reword the explanation differently to make this more clear. We could say. "Copy the home page for your website, if it exists, into the `/var/www/html` directory. Otherwise, create a simple `index.html` file in that directory to represent the eventual home page." Or something like that. If it is confusing to you, it will probably be confusing to others, so it should be reworked.

Got it, I was thinking on same lines. The contents of index.html page can be anything for testing right?

**Comment by JeffreyNovotny** [comment]
> Got it, I was thinking on same lines. The contents of index.html page can be anything for testing right?

Yes that's right. A very simple .html page will suffice. Even a file with a line of text or two for testing is okay. Just something to confirm that the web server is serving the page in that directory to a client browser

**Review by leslitagordita — APPROVED** [review]

**Pull request merged**
