### PR TITLE
Nginx Tuning and Performance

### PR DESCRIPTION
**Pull request by bobstrecansky**
Creating a  document for NGINX tuning and performance

### CODE REVIEW

**Comment by FelicianoTech** [comment]
I've submitted the following pull request against your branch. Please review notes attached to the PR. https://github.com/bobstrecansky/docs/pull/1

**Comment by FelicianoTech** [comment]
@bobstrecansky Will you have a chance to review/act on my notes from my PR you merged?

**Comment by bobstrecansky** [comment]
@FelicianoTech I approved your notes and approve them.

**Comment by alexfornuto** [comment]
I think @FelicianoTech was asking you to include changes based on those notes to the PR, although I see how it wasn't really specified that way.

**Comment by alexfornuto** [comment]
@bobstrecansky why did you close this PR? Did you no longer want us to use this guide?

**Comment by bobstrecansky** [comment]
Alex,


I merged the changes into my document; do you need me to re-open it in
order to utilize it?

Thanks,

Bob

**Comment by alexfornuto** [comment]
@bobstrecansky closing the PR indicated that you don't want the changes merged into our repository. I see that you merged @FelicianoTech's PR,  but he also made some requests for additional information. They were:

```
Logging:

present the option of turning logging off completely if they alternative logging methods

Activity Monitoring:

we could mention Linode Longview in this section as a way to do this
```

Are you willing and able to make adjustments based on these notes? If not, please let us know.

**Comment by bobstrecansky** [comment]
Alex,

Yup; i'll add these additional changes.

**Comment by alexfornuto** [comment]
:+1:

**Comment by bobstrecansky** [comment]
@alexfornuto and @FelicianoTech,

Completed; please check out my pull request and let me know if you would like anything additional.

**Comment by bobstrecansky** [comment]
Alex,

Saw you removed the waiting on Author tag; is there anything else you need from me before this is published?

**Comment by FelicianoTech** [comment]
I will run through your guide again for another tech test and if everything is good to go, it will proceed to a copy edit. Nothing is needed from you at this moment.

**Comment by FelicianoTech** [comment]
Proceeding to copy edit.

**Comment by ellekrout** [comment]
Hello, @bobstrecansky! Just letting you know I'm getting to the copy edit of this today. My apologies for the delay in responses.

**Comment by ellekrout** [comment]
And we're done the copy edit! You should have PR waiting for you with my changes. If everything looks good, let us know and we can proceed with publication!

Thank you!

**Comment by bobstrecansky** [comment]
Elle,

Approved the document!

Thanks,

Bob

**Comment by alexfornuto** [comment]
@bobstrecansky please merge @ellekrout's PR so that her changes get pulled into your PR.

**Comment by ellekrout** [comment]
Once the above is done, we can proceed with publication. If you would like to let us know your Paypal-associated email or Linode account, we can either pay you via Paypal or Linode credit -- just let us know which you prefer! Feel free to let us know here, for via email: contribute@linode.com.

Thank you again for your contribution!

**Comment by alexfornuto** [comment]
@bobstrecansky we still need you to to merge https://github.com/bobstrecansky/docs/pull/2

**Comment by bobstrecansky** [comment]
Alex,

Merged https://github.com/bobstrecansky/docs/pull/2

**Comment by ellekrout** [comment]
Thanks @bobstrecansky! Now, as mentioned above:  If you would like to let us know your Paypal-associated email or Linode account, we can either pay you via Paypal or Linode credit -- just let us know which you prefer! Feel free to let us know here, for via email: contribute@linode.com.

**Comment by bobstrecansky** [comment]
Elle, A linode credit to my account should be fine.

**Comment by ellekrout** [comment]
@bobstrecansky Can you please provide us with either your Linode username or email so I can confirm I'll be crediting the correct account?

**Comment by bobstrecansky** [comment]
@ellekrout my email is bob.strecansky@gmail.com

**Comment by alexfornuto** [comment]
@bobstrecansky Why do you keep closing this Pull Request?

**Comment by bobstrecansky** [comment]
Sorry @alex, thought I should close it when I was finished.

**Comment by alexfornuto** [comment]
No, a Pull Request remains open until it's merged. When it's closed that means it either is already merged, or isn't going to be merged.

**Comment by ellekrout** [comment]
Your guide is now live at: https://linode.com/docs/websites/nginx/configure-nginx-for-optimized-performance

Your account has also been credited $250. Thank you for contributing to Linode docs!

**Pull request merged**
