### PR TITLE
Configuring StartSSL with Apache on Debian or Ubuntu

### PR DESCRIPTION
**Pull request by dreamerblue**
This is a guide about StartSSL and its application. The original version refers to PR [#275](https://github.com/linode/docs/pull/275).

### CODE REVIEW

**Comment by alexfornuto** [comment]
What are the pros / cons of using the StartSSL "Express Lane" versus signing up for an account?

**Comment by alexfornuto** [comment]
Unfortunately I'm unable to review this because I already have a StartSSL account. The next available team member will take a look.

**Comment by dreamerblue** [comment]
@alexfornuto @cwlinode Thanks for suggestion. I have modified the description of Express Lane.

**Comment by cwlinode** [comment]
@dreamerblue 

We've decided to reorganize and restructure our guides which deal with TLS certificate installations. Since Let's Encrypt is publicly available now, we're also choosing to focus on that project for exemplary purposes rather than StartSSL Free.

We'll preserve elements from our current guide on nginx with StartSSL for readers still interested in that certificate brand, but unfortunately we will not be adding any further material on StartSSL at this time.

**Pull request closed without merging**
