### PR TITLE
[NEW] Install Magento on Ubuntu 18.04

### PR DESCRIPTION
**Pull request by Darkstar90**
### Major Changes

- Added Magento-compatible LAMP stack installation instructions
- Improved readability in select sections

### CODE REVIEW

**Comment by andystevensname** [comment]
Missing screenshots for steps 2, 3, and 4 of 'Secure your Site with SSL': magento-stores-config.png, magento-general-web.png, and magento-secure-base-url.png.

**Comment by Guaris** [comment]
@Darkstar90 ^ Check above.

**Comment by Darkstar90** [comment]
I'll have this one addressed today.

**Comment by Darkstar90** [comment]
Hey Andy,

The missing image files have now been uploaded. Let me know if anything else is needed from me.

-Andrew

**Comment by andystevensname** [comment]
Thanks, looking good.

**Pull request merged**
