### PR TITLE
Add proxy_params configuration instead of verbatim proxy commands

### PR DESCRIPTION
**Pull request by simos**
When using nginx as a reverse proxy, nginx has a ready-made configuration file to add proxy commands. It is `/etc/nginx/proxy_params`.

In the tutorial I did not include the file but added verbatim some of the lines of the configuration file.
With this change, the configuration file is used instead.

### CODE REVIEW

**Comment by simos** [comment]
I need this change because I am writing a new tutorial that requires it.

**Comment by nmelehan** [comment]
Deploy preview for *nostalgic-ptolemy-b01ab8* ready!

Built with commit 35638de15b51e5b9ba8504423155d3313019f40c

https://deploy-preview-3382--nostalgic-ptolemy-b01ab8.netlify.app

**Comment by simos** [comment]
This change is required for https://github.com/linode/docs/pull/3403

**Comment by simos** [comment]
@nmelehan Can you please apply this change?

**Review by wildmanonline — APPROVED** [review]

**Comment by wildmanonline** [comment]
Hi @simos. Sorry for the delay here. I've just validated the changes you made to your original guide and we're ready to merge this in shortly.

**Review by nmelehan — APPROVED** [review]

**Pull request merged**
