### PR TITLE
McMyAdmin on Ubuntu 14.04 guide

### PR DESCRIPTION
**Pull request by agottschling**

### CODE REVIEW

**Comment by alexfornuto** [comment]
We already have a guide on McMyAdmin: https://www.linode.com/docs/applications/game-servers/minecraft-with-mcmyadmin-on-debian

**Comment by agottschling** [comment]
That one's for debian, but I see where you're going. Alright then. I'll move on to other ideas. Is there a was that I can submit ideas to make sure that I don't run into this issue again?

**Comment by alexfornuto** [comment]
Sure, you can always email contribute@linode.com. Perchance, have you tried using out existing guide for Debian on Ubuntu?

**Comment by agottschling** [comment]
I looked it over and it's basically the same as mine. Thanks much.

**Pull request closed without merging**
