### PR TITLE
Pritunl VPN on Ubuntu 14.04

### PR DESCRIPTION
**Pull request by agottschling**

### CODE REVIEW

**Comment by thetechstewart** [comment]
@agottschling - thanks for the new submission!  I'll give this guide a once over and see whether it's a good candidate for inclusion in our guides and tutorials.

**Comment by agottschling** [comment]
@thetechstewart Any update on this PR's status?

**Comment by ellekrout** [comment]
Hi @agottschling! This is ready for publication! Let us know if you want to receive payment via Linode credit or PayPal, let us know on here or through contribute@linode.com. Be sure to let us know any relevant account details (PayPal email or Linode account).

Thank you!

**Comment by agottschling** [comment]
Paypal at my email address. Do you have it?

**Comment by agottschling** [comment]
if not, it is andrewgottschlingATgmxDOTus

**Comment by ellekrout** [comment]
Hello! Your guide is now live here: https://www.linode.com/docs/networking/vpn/pritunl-vpn-ubuntu

I've forwarded your email to our billing team, and you should receive payment shortly! Thank you for your contribution to Linode Docs!

**Pull request merged**
