### PR TITLE
Patch -- Update to reflect new Google API console

### PR DESCRIPTION
**Pull request by scottinthebooth**
new product name
new other application
new oauth2
new credentials
new configure screen small
new configure screen
new api credential

### CODE REVIEW

**Comment by ellekrout** [comment]
Awesome! Thank you! Pushing this to a copy edit now, 

By the way, since you mentioned being new to Git, have you checked out our [GitHub Guide](https://linode.com/docs/github-guide)? It's geared specifically towards getting people set up to submit guides. It might help!

**Comment by scottinthebooth** [comment]
I will check it out!!  Thanks!

Scott

**Comment by thetechstewart** [comment]
@scottinthebooth - I've been reviewing your copy edits, however the image filenames that you uploaded don't seem to match up with the ones listed in your file.  Could you update this PR with the images placed in your branch's "assets" folder?  You'll also need to remove any spaces from image names and the image tags within the guide.

Thanks!

**Comment by scottinthebooth** [comment]
I'm trying to make the updates as requested but every time I clone or download the repository I don't see the files from my guide.  I'm new to git and trying to follow the tutorial but so far I'm not having any luck.  I'll let you know as soon as I can get it to cooperate

**Comment by ellekrout** [comment]
Hey Scott!

When you're in the repo you should be able to navigate through folders: Have you checked in the docs/assets folder for the images? And the doc itself was moved to docs/applications/cloud-storage/access-google-drive-linode.md.

If you're still having trouble, please let us know. We're happy to help out! :)

**Comment by scottinthebooth** [comment]
I traded a couple e-mails with github support and they got me going.  I was
cloning the main repository rather than my patch.  I'll finish up these
edits this evening and hopefully have them to you by tomorrow morning.

Scott

**Comment by ellekrout** [comment]
Awesome! Glad they could help you out! Looking forward to your updates!

**Comment by scottinthebooth** [comment]
OK, I added a new commit with the images in the assets folder and no spaces in the names.  When I view the guide on github.com now everything shows up properly

**Comment by scottinthebooth** [comment]
@thetechstewart did the new pictures come through OK?

**Comment by thetechstewart** [comment]
@scottinthebooth: I've just pulled down your changes, and the images look good.  I'll finish up your copy edit today and submit any changes I have for review.

**Comment by ellekrout** [comment]
Hey @scottinthebooth! I noticed you merged James's PR, but not to this branch. That's fine! But if you can make a new PR against your master branch with the finished guide, we can proceed with payment, etc.

Also: please let us know how you would like to receive payment: Through PayPal or through account credit. Thank you!

**Comment by scottinthebooth** [comment]
Lets do PayPal please, my account is scottinthebooth@gmail.com.  I did a new pull request, please let me know if you get what you needed!  Almost got my head wrapped around this whole GitHub thing :-P

**Comment by ellekrout** [comment]
You made the PR against scottinthebooth/docs master, not Linode/docs master. Once more with feeling? :P 
Git can be very confusing, so no worries. You'll get the hang of it. We still make mistakes over here all the time. :)

**Pull request closed without merging**
