### PR TITLE
Setting Up an Offsite Ubiquiti UniFi Controller on Ubuntu 14.04

### PR DESCRIPTION
**Pull request by seanthewebber**
Completed tutorial

### CODE REVIEW

**Comment by alexfornuto** [comment]
1) This PR also includes a guide on Roundcube.

2) What are the pros / cons of setting up this system, designed to be in the same LAN as the devices it manages, on an external cloud server?

**Comment by seanthewebber** [comment]
1) Oh dear. I guess I forgot to make a separate branch for the Roundcube tutorial (pull request #348). Can this be ignored, and if not, how can I fix it?

2) I outlined the those points in the **Pros and Cons** section of the tutorial. What should I specifically add so that it better explains your question? :)

**Comment by alexfornuto** [comment]
`Requires Enterprise-grade edge router(s) that support custom DHCP and DNS options`

Meaning not what you would likely have in your home?

**Comment by seanthewebber** [comment]
Yes and no. You can load custom firmware (like DD-WRT and OpenWRT) onto consumer grade routers that **do** support those features, but the stock firmware that most wireless routers ship with **do not** support them.

However, somebody that would be a likely Linode reader (computer enthusiast, sysadmin, or tinker-er) has probably flashed custom firmware or owns a business-grade firewall (in my case, pfSense) at home already.

I envision running an offsite UniFi Controller being most beneficial to a organization with many branch offices/buildings/locations with UniFi APs. Remotely logging into each and every AP throughout an entire organization to make one configuration change is inhumane. This setup reduces those hours of mundane data entry into a few mouse clicks that apply across the entire org.

**Comment by tknarr** [comment]
Suggestion then, Sean, as someone who routinely flashes new routers with DD-WRT: mention that as an alternative in the doc, or just state what capabilities the router needs. A pfSense box would be what I'd call a business-grade router, enterprise-grade would be something at least rack-mounted, a consumer router with DD-WRT flashed on it wouldn't qualify as either business- or enterprise-grade equipment but it's certainly entirely suitable for a small office.

**Comment by seanthewebber** [comment]
Thanks @tknarr! I've gone ahead and updated my guide to reflect your suggestion.

**Comment by cwlinode** [comment]
@scottinthebooth Thank you for submitting this, but we have chosen not to accept this guide. We don't have any Ubiquity equipment on hand to test with, and we're also concerned with the security implications of passing router configurations over the public internet.

**Comment by scottinthebooth** [comment]
I didn't submit anything on Ubiquiti networks...

Scott

**Comment by cwlinode** [comment]
Heh! Sorry bout that.

**Comment by seanthewebber** [comment]
@cwlinode I also contemplated the security aspect at first, but went for it once I discovered the UniFi Controller makes its connections over HTTPS/TLS. [Ubiquiti hosts a guide about installing that controller on Amazon AWS](https://help.ubnt.com/hc/en-us/articles/209376117-UniFi-Install-a-UniFi-Cloud-Controller-on-Amazon-Web-Services), which is where I derived bits of this tutorial from. It was updated a month and a half ago, too. I doubt they would be hosting and updating a tutorial that is insecure.

The [UniFi AP AC LR](https://www.ubnt.com/unifi/unifi-ap-ac-lr/) I used to write this tutorial is sitting behind me in a box. I would be happy to loan it to your editorial department, should you reconsider accepting this guide.

**Pull request closed without merging**
