### PR TITLE
Visualizing Apache Webserver Logs in the ELK Stack

### PR DESCRIPTION
**Pull request by tylerjl**
Howdy!

This is a guide for setting up an ELK stack on Debian 8 using Apache logs for sample data. It goes from zero to running with Kibana with live Apache logs, though I didn't go into dashboarding in-depth as the guide got pretty long (possibly room for further work there.)

Let me know about any feedback/next steps!

### CODE REVIEW

**Comment by ellekrout** [comment]
Hey @tylerjl! This is a great guide, and while it gave me trouble at points, it works perfectly. There's a pull request waiting against your branch (tylerjl/linode-docs#1) with a few changes I made for clarity: 

I altered the early step `sudo tail /var/log/apache2/access.log` to fall in line with the location of the access log set up within the Apache on Debian 8 guide linked earlier. The initial command is still there, but I added a note to help any confused users.

I also encountered a native support error while initially starting Logstash, but since it was an easy one-line fix, I implemented that as a note, as well.

The final issue I had was getting Kibana to load in-browser, but that was because I forgot to open up my Firewall rules. Regardless, since I'm probably not the only person to forget that and won't be the last, I added an "insert iptables rule" step to the opening steps.

An additional section on the dashboard would be a great addition, I think. Even with the guide at it's current length, I htink giving the readers some basics to go off of would be great instead of sending them straight to Kibana's documentation. This doesn't have to be very in-depth -- just give someone who has never used Kibana something to start with, so they're off on the right foot.

Thank you!

**Comment by tylerjl** [comment]
Great feedback, thank you!

I've amended the guide with your suggestions. There's now a short guide to creating a chart towards the end of the final section.

In addition, I've added a completed example dashboard to the beginning of the guide to demonstrate the types of visualizations Kibana is capable of - I'm not sure if there's a precedence for cover/summary screenshots for guides, so let me know if that works or should be changed/removed.

**Comment by ellekrout** [comment]
Awesome, @tylerjl! I'll be review the changes sometime tomorrow, so you should hear from me with any additional comments then. If not, your guide has been moved to the copy edit phase, and you should then be hearing from one of my coworkers as soon as that edit is done.

**Comment by ellekrout** [comment]
Everything looks great! There's one more PR on my end (I put in the wrong port for the updated firewall rules, shhhh) -- tylerjl/linode-docs#2. I also moved the cover screenshot to below the introduction paragraph.

Once that's merged, we'll go ahead with getting this copy edited. :)

**Comment by tylerjl** [comment]
LGTM!

Looks good to me

**Comment by ellekrout** [comment]
Awesome! I've assigned this out for copy edit, and you should be hearing from your copy editor, Keith, in a day or so with any grammar tweaks, etc.

**Comment by ellekrout** [comment]
Heya! Just letting you know you have a copy edit PR waiting for your review at tylerjl/linode-docs#3. :)

**Comment by tylerjl** [comment]
Excellent feedback via the copy edit; I've merged the fixes and tweaked one line for technically accuracy.

Let me know if you need anything else on my side! :pizza:

**Comment by ellekrout** [comment]
Awesome! There's one last PR for you here: tylerj/linode-docs#4

As much as I love the "Pre-Flight Checklist," I've (begrudgingly) had to set it to our usual style of titles. Once you've checked out and merged the PR, we'll get you published and paid. If you can confirm your email and preferred payment method, I'll forward your information to billing. :)

**Comment by tylerjl** [comment]
Super; PR merged and payment details sent. :airplane:

**Pull request merged**
