### PR TITLE
[Update] How to Install and Configure the Caddy Web Server on Ubuntu …

### PR DESCRIPTION
**Pull request by Rajakavitha1**
…18.04

- Updated the guide based on the latest updates from the official documentation
- fixes https://github.com/linode/docs/issues/4406

### CODE REVIEW

**Comment by nmelehan** [comment]
:heavy_check_mark: Deploy Preview for *nostalgic-ptolemy-b01ab8* ready!


:hammer: Explore the source changes: 090aaf4b969b44d885fccef80ff1db7b866c47d3

:mag: Inspect the deploy log: [https://app.netlify.com/sites/nostalgic-ptolemy-b01ab8/deploys/60c4a0df787ad10008770769](https://app.netlify.com/sites/nostalgic-ptolemy-b01ab8/deploys/60c4a0df787ad10008770769?utm_source=github&utm_campaign=bot_dl)

:sunglasses: Browse the preview: [https://deploy-preview-4407--nostalgic-ptolemy-b01ab8.netlify.app](https://deploy-preview-4407--nostalgic-ptolemy-b01ab8.netlify.app?utm_source=github&utm_campaign=bot_dp)

**Comment by francislavoie** [comment]
These changes are not sufficient. The Caddyfile config still uses Caddy v1 syntax, and the guide uses CLI flags that no longer exist in Caddy v2.

IMO this guide (and other Caddy guides like it) should simply be deleted. https://github.com/linode/docs/issues/4572

The official documentation should be the primary reference. https://caddyserver.com/docs/

We're trying to fight misinformation here, we get users using these guides coming to our community forums, confused because of inaccurate guides.

**Comment by Rajakavitha1** [comment]
Hi @mholt and @francislavoie  I have updated and validate the steps in the Debian, Ubuntu, and CentOS distros and updated the guides: https://github.com/linode/docs/pull/4688/

I will update the archlinux guide sometime next week

**Comment by andystevensname** [comment]
Hey Rajie, please take a look at this guide and let us know if we can close it.

**Comment by Rajakavitha1** [comment]
> #4688

Hi @andystevensname !!! The updates were made in[4688 ](https://github.com/linode/docs/pull/4688). Closing this PR.

**Pull request closed without merging**
