### PR TITLE
[NEW] Automate Browsing with Nightmarejs

### PR DESCRIPTION
**Pull request by GuessWhoSamFoo**
Freelancer contact: nashruddin.amin@gmail.com

### CODE REVIEW

**Comment by GuessWhoSamFoo** [comment]
[Automate Browsing Tasks Using Nightmare.js (Nash A)](https://trello.com/c/rK4yoO8G/487-automate-browsing-tasks-using-nightmarejs-nash-a)

**Comment by flowfree** [comment]
Is there any update with this PR? I also don't have access to the Trello board.

**Comment by GuessWhoSamFoo** [comment]
There's a backlog currently. Probably will be reviewed by the end of this week.

**Comment by kcraig34** [comment]
@GuessWhoSamFoo @Jskobos -- Can either of you give a status check on this guide? It doesn't seemed to be published yet. Thanks.

**Pull request merged**
