### PR TITLE
SteamCMD: Installation using package from repositories

### PR DESCRIPTION
**Pull request by davidebeatrici**
The "steamcmd" package is currently available in Debian Testing and Ubuntu Xenial\Yakkety.

### CODE REVIEW

**Comment by pbzona** [comment]
Hi @davidebeatrici 

Thanks for your contribution. I'm going to double check to make sure this works as expected - I'll get back to you shortly.

**Comment by pbzona** [comment]
@davidebeatrici I've made a pull request with some additional changes here:

https://github.com/davidebeatrici/docs/pull/3

Were you able to install the SteamCMD package on a Debian system? I wasn't able to get it from the testing or stretch repos, although according to their directory it is included like you said.

**Comment by davidebeatrici** [comment]
@pbzona The [package](https://packages.debian.org/stretch/steamcmd) is available only in the _non-free_ area of Debian's repository.

Should I write it in the guide?

**Comment by pbzona** [comment]
@davidebeatrici Makes sense, that's probably why I didn't see it. Yes, if you could add that step I think it would be helpful. Once that's done I'll have a look and merge this PR. Thanks!

**Comment by davidebeatrici** [comment]
@pbzona Done, you're welcome!

**Comment by pbzona** [comment]
@davidebeatrici Perfect! I'll get this merged and your changes should be published in a few minutes. Thanks again 👍

**Pull request merged**
