### PR TITLE
Using Docker in Production

### PR DESCRIPTION
**Pull request by bobstrecansky**
Using a sample Docker / NGINX / Flask & Gunicorn / Redis / Postgres application to explain the utilization of docker-compose and running multiple containers simultaneously.

### CODE REVIEW

**Comment by bobstrecansky** [comment]
@GuessWhoSamFoo - I also meant to mention - if we want to deep dive into the application a little more, i'm happy to include that in this PR.

**Comment by Guaris** [comment]
@bobstrecansky Can you please send `ArchitectureDiagram.svg` referenced in line 24 of the doc? Feel free to submit it as a PR or via email to docs@linode.com

**Comment by bobstrecansky** [comment]
@Guaris - added!

**Comment by Guaris** [comment]
closed in favor of #1364

**Pull request closed without merging**
