### PR TITLE
How to deploy a flask app with uwsgi and nginx in ubuntu 14.04

### PR DESCRIPTION
**Pull request by Michael-Jalloh**

### CODE REVIEW

**Comment by pbzona** [comment]
Hi @Michael-Jalloh 

Thanks for your submission. This is an interesting concept, but I'm curious about the title. The file you submitted seems to be a guide on deploying a Flask application - was there a different guide you meant to submit or was the PR title an error?

I like what you have so far, but I don't think it's comprehensive enough to warrant a new guide in its current form. I think it could use more description for the individual steps, specifically where you are building the app and writing the upstart script. We're currently unable to accept this guide and as such I'll be closing this pull request. However, I'd encourage you to submit an updated version with more content. We'd love to work with you to develop this into something that may fit into our library.

Thanks,

Phil Zona

**Comment by Michael-Jalloh** [comment]
The title was an error. Trying to get use to working git. 

I can update my guide. Its an open source light weight flask blog I built. I will try and work more on my guide. Where exactly do you want me to update

**Comment by pbzona** [comment]
We're more interested in the administrative side of things (configuring nginx to properly serve the app, etc.) than building the app itself. So what I'd like to see is more expansion on the steps of setting it up. You can leave app.py as it is rather than walking through how to create a working blog, since it will serve mainly as a test application.

Are there any steps where things could potentially go wrong if the user is not careful? If so, be sure to expand those. You may also want to consider information on how to tune Nginx for app hosting as opposed to website hosting. Are there any major differences that the user should be aware of? Things like that would be good starting points.

**Comment by Michael-Jalloh** [comment]
Ok. I think I can do that. Should I open a new pull request

**Comment by pbzona** [comment]
You can just commit any changes to your local branch (the same one you used when creating this guide) and push them to make them show up here. I'll reopen the pull request and subscribe so that I get updates.

**Comment by Michael-Jalloh** [comment]
Thanks.

**Comment by Michael-Jalloh** [comment]
I updated the guide

**Comment by pbzona** [comment]
Hi @Michael-Jalloh, 

Thanks for your patience. I've been assigned to start reviewing and testing your guide. Over the next few days I'll be working through it to make sure the instructions are clear and consistent with our style, so please hold off on making any commits during that time unless absolutely necessary. Once finished, I'll submit a pull request against your branch. Feel free to reach out with any questions.

**Comment by pbzona** [comment]
@Michael-Jalloh Running into a problem when I try to test uWSGI - the output reads in part:

"ImportError: No module named py"

When I visit my IP in a browser, it returns an internal server error.

I'm admittedly not very familiar with Flask, but I see no point where it should be trying to reference a module named "py." Are there other steps that need to be taken before this? I'm going to research it myself, but maybe you could save me some time if you've seen this or know what it means.

**Comment by Michael-Jalloh** [comment]
Which step was that.

**Comment by Michael-Jalloh** [comment]
No need to do the research. I can fix it

**Comment by Michael-Jalloh** [comment]
Can I see the wsgi.py file that u trying to use.

**Comment by Michael-Jalloh** [comment]
Its seems you are trying to import a module name 'py'. That's the error

**Comment by Michael-Jalloh** [comment]
The problem is that the formatting isn't right.  Let me change the formatting.

**Comment by pbzona** [comment]
@Michael-Jalloh Thanks for taking a look. Can I expect a more substantial commit soon? It seems the only change you made to the code is correcting a typo on the commit "import" which I recognized and applied when I tried this.

Are there other configuration changes that need to be made before testing uwsgi.py? Here's a more complete version of the output I got when I tried to start it:

https://gist.github.com/pbzona/c7c0f09b216dfaf7f299dab919acbc4c

I've followed the guide exactly as specified with no additional configuration. If there's something else that needs to be done, it's not a problem, I am just not sure why it's returning this ImportError. 

The expected result is that the app ("Hello I'm a flask app") should be displayed when running the command `uwsgi --socket '0.0.0.0:5000' --protocol=http -w wsgi.py` correct?

**Comment by Michael-Jalloh** [comment]
Its should be wsgi.py not uwsgi.py

**Comment by pbzona** [comment]
Error on my part in typing the comment, but I named the file wsgi.py and called it that in the command.

**Comment by Michael-Jalloh** [comment]
On github the format isn't right.
it suppose to be

from app application

if __name__ == '__main__':
     application.run()

**Comment by pbzona** [comment]
I don't think the GitHub formatting is the issue for me, and I'm familiar with Python syntax. You're right, wsgi.py is trying to import the `py` module, but I'm just not seeing why or where it's trying to do that.

**Comment by pbzona** [comment]
Ah, I think I found the problem. I ran the uwsgi command to test and added `--module=wsgi`. Apparently that's where the error was coming from - I am assuming that it was trying to use a default module or something and that's why it wasn't working. I'll continue to test, thanks for your help.

**Comment by Michael-Jalloh** [comment]
Ok.

**Comment by pbzona** [comment]
@Michael-Jalloh After further research, we will be unable to publish this guide for a number of reasons, including but not limited to writing style, lack of proper formatting, and technical inaccuracies in many sections. In addition, I found a number of similarities between your guide and a previously published tutorial on the same subject.

Because we only publish original content that is technically sound, we will be unable to accept your submission and I will be closing this pull request. Thank you.

**Pull request closed without merging**
