### PR TITLE
[New] Kubernetes Advantages

### PR DESCRIPTION
**Pull request by andystevensname**

### CODE REVIEW

**Comment by nmelehan** [comment]
Deploy preview for *nostalgic-ptolemy-b01ab8* ready!

Built with commit bb709e3de9e26893f3c9c396937e19bab49f8663

https://deploy-preview-2707--nostalgic-ptolemy-b01ab8.netlify.com

**Comment by andystevensname** [comment]
Please don't tech edit this guide just yet, I'm working on adding a paragraph about managed Kubernetes that will need to be included first.

**Comment by andystevensname** [comment]
Ready for tech edit.

**Comment by nmelehan** [comment]
Haven't uploaded the diagrams yet, but this is ready for a copy edit in the meantime

**Pull request merged**
