### PR TITLE
Initial draft of Apache Kafka guides

### PR DESCRIPTION
**Pull request by JeffreyNovotny**

### CODE REVIEW

**Comment by nmelehan** [comment]
Deploy preview for *nostalgic-ptolemy-b01ab8* ready!

Built with commit aa99a6130f013ef1cfaa4d16f140f052885c9cd5

https://deploy-preview-3931--nostalgic-ptolemy-b01ab8.netlify.app

**Review by andystevensname — CHANGES_REQUESTED** [review]

**Comment by Sachin-Suresh** [comment]
Hi @JeffreyNovotny, 

In the Kafka installation guide, when I try to run Kafka using `bin/zookeeper-server-start.sh config/zookeeper.properties`, I get the following error:

```
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000e0000000, 536870912, 0) failed; error='Not enough space' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 536870912 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /home/kafka/kafka-2.8.0-src/hs_err_pid12667.log
```

Do you suggest any resolution to this error?

**Comment by JeffreyNovotny** [comment]
Hi @Sachin-Suresh,

What type of Linode are you running? I configured this on a 4G Linode and did not have any problems. JDK is a bit of a memory hog and there is a chance that memory requirements have increased even further in the few months since I wrote this.

If you are using a smaller Linode,  you could try switching to a 4G. But you could also try configuring some swap space. It would run more sluggishly but would still work. Are there other applications running on your Linode and using memory? What do commands like "free", "top", and "vmstat" show?

We probably want to add a note that a more robust Linode is recommended for this application.

Regards,
Jeff

> Hi @JeffreyNovotny,
> 
> In the Kafka installation guide, when I try to run Kafka using `bin/zookeeper-server-start.sh config/zookeeper.properties`, I get the following error:
> 
> ```
> OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000e0000000, 536870912, 0) failed; error='Not enough space' (errno=12)
> #
> # There is insufficient memory for the Java Runtime Environment to continue.
> # Native memory allocation (mmap) failed to map 536870912 bytes for committing reserved memory.
> # An error report file with more information is saved as:
> # /home/kafka/kafka-2.8.0-src/hs_err_pid12667.log
> ```
> 
> Do you suggest any resolution to this error?
> 
> Some StackOverflow forums suggested to change the memory here:
> 
> `/home/kafka/kafka_2.13-2.7.0/bin/kafka-server-start.sh`
> 
> From:
> 
> `export KAFKA_HEAP_OPTS="-Xmx1G -Xms1G"`
> 
> To
> 
> `export KAFKA_HEAP_OPTS="-Xmx256M -Xms128M"`
> 
> But, I could not find any fix to this.

**Comment by Sachin-Suresh** [comment]
> Hi @Sachin-Suresh,
> 
> What type of Linode are you running? I configured this on a 4G Linode and did not have any problems. JDK is a bit of a memory hog and there is a chance that memory requirements have increased even further in the few months since I wrote this.
> 
> If you are using a smaller Linode, you could try switching to a 4G. But you could also try configuring some swap space. It would run more sluggishly but would still work. Are there other applications running on your Linode and using memory? What do commands like "free", "top", and "vmstat" show?
> 
> We probably want to add a note that a more robust Linode is recommended for this application.
> 
> Regards,
> Jeff
> 
> > Hi @JeffreyNovotny,
> > In the Kafka installation guide, when I try to run Kafka using `bin/zookeeper-server-start.sh config/zookeeper.properties`, I get the following error:
> > ```
> > OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000e0000000, 536870912, 0) failed; error='Not enough space' (errno=12)
> > #
> > # There is insufficient memory for the Java Runtime Environment to continue.
> > # Native memory allocation (mmap) failed to map 536870912 bytes for committing reserved memory.
> > # An error report file with more information is saved as:
> > # /home/kafka/kafka-2.8.0-src/hs_err_pid12667.log
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Do you suggest any resolution to this error?
> > Some StackOverflow forums suggested to change the memory here:
> > `/home/kafka/kafka_2.13-2.7.0/bin/kafka-server-start.sh`
> > From:
> > `export KAFKA_HEAP_OPTS="-Xmx1G -Xms1G"`
> > To
> > `export KAFKA_HEAP_OPTS="-Xmx256M -Xms128M"`
> > But, I could not find any fix to this.

Just Updated my query @JeffreyNovotny, there seems to be a class not found issue.

**Comment by JeffreyNovotny** [comment]
@Sachin-Suresh: I did some brief research and this was an issue with some older releases in which the Zookeeper was downloaded/installed separately. Is your JDK version still 11.0.9.1? And your Kafka version 2.13.2.7? Are you using Ubuntu 20.04?

I don't have any obvious answers to this. This guide is from over four months ago and the application is no longer configured on my machine so I can't quickly check into this. I could try reconfiguring it when I have the opportunity if you can't get it working.

> > Hi @Sachin-Suresh,
> > What type of Linode are you running? I configured this on a 4G Linode and did not have any problems. JDK is a bit of a memory hog and there is a chance that memory requirements have increased even further in the few months since I wrote this.
> > If you are using a smaller Linode, you could try switching to a 4G. But you could also try configuring some swap space. It would run more sluggishly but would still work. Are there other applications running on your Linode and using memory? What do commands like "free", "top", and "vmstat" show?
> > We probably want to add a note that a more robust Linode is recommended for this application.
> > Regards,
> > Jeff
> > > Hi @JeffreyNovotny,
> > > In the Kafka installation guide, when I try to run Kafka using `bin/zookeeper-server-start.sh config/zookeeper.properties`, I get the following error:
> > > ```
> > > OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000e0000000, 536870912, 0) failed; error='Not enough space' (errno=12)
> > > #
> > > # There is insufficient memory for the Java Runtime Environment to continue.
> > > # Native memory allocation (mmap) failed to map 536870912 bytes for committing reserved memory.
> > > # An error report file with more information is saved as:
> > > # /home/kafka/kafka-2.8.0-src/hs_err_pid12667.log
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Do you suggest any resolution to this error?
> > > Some StackOverflow forums suggested to change the memory here:
> > > `/home/kafka/kafka_2.13-2.7.0/bin/kafka-server-start.sh`
> > > From:
> > > `export KAFKA_HEAP_OPTS="-Xmx1G -Xms1G"`
> > > To
> > > `export KAFKA_HEAP_OPTS="-Xmx256M -Xms128M"`
> > > But, I could not find any fix to this.
> 
> Just Updated my query @JeffreyNovotny, there seems to be a class not found issue.

**Comment by Sachin-Suresh** [comment]
@JeffreyNovotny, Yes I am using Ubuntu 20.04 with JDK `11.0.11` and `kafka-2.8.0`, the latest build.

**Comment by JeffreyNovotny** [comment]
> @JeffreyNovotny, Yes I am using Ubuntu 20.04 with JDK `11.0.11` and `kafka-2.8.0`, the latest build.

@Sachin-Suresh: Okay, I'll investigate this later today.

**Comment by Sachin-Suresh** [comment]
> > @JeffreyNovotny, Yes I am using Ubuntu 20.04 with JDK `11.0.11` and `kafka-2.8.0`, the latest build.
> 
> @Sachin-Suresh: Okay, I'll investigate this later today.

But, I tried for the same version which is used in the guide, and that works! Not the latest version though.

**Comment by JeffreyNovotny** [comment]
> > > @JeffreyNovotny, Yes I am using Ubuntu 20.04 with JDK `11.0.11` and `kafka-2.8.0`, the latest build.
> > 
> > 
> > @Sachin-Suresh: Okay, I'll investigate this later today.
> 
> But, I tried for the same version which is used in the guide, and that works! Not the latest version though.

There must be a version mismatch between JDK and Kafka somehow. I have to leave for an appointment, but will do some digging later on today.

**Comment by JeffreyNovotny** [comment]
> There must be a version mismatch between JDK and Kafka somehow. I have to leave for an appointment, but will do some digging later on today.

I tested with v2.8 and the latest version of Java. It worked for me. I was able to start Zookeeper:

/home/kafka28/kafka_2.13-2.8.0$ bin/zookeeper-server-start.sh config/zookeeper.properties
[2021-06-07 13:50:37,002] INFO Reading configuration from: config/zookeeper.properties (org.apache.zookeeper.server.quorum.QuorumPeerConfig)
[2021-06-07 13:50:37,003] WARN config/zookeeper.properties is relative. Prepend ./ to indicate that you're sure! (org.apache.zookeeper.server.quorum.QuorumPeerConfig)
[2021-06-07 13:50:37,015] INFO clientPortAddress is 0.0.0.0:2181 (org.apache.zookeeper.server.quorum.QuorumPeerConfig)
[2021-06-07 13:50:37,015] INFO secureClientPort is not set (org.apache.zookeeper.server.quorum.QuorumPeerConfig)
[2021-06-07 13:50:37,019] INFO autopurge.snapRetainCount set to 3 (org.apache.zookeeper.server.DatadirCleanupManager)
[2021-06-07 13:50:37,019] INFO autopurge.purgeInterval set to 0 (org.apache.zookeeper.server.DatadirCleanupManager)
[2021-06-07 13:50:37,019] INFO Purge task is not scheduled. (org.apache.zookeeper.server.DatadirCleanupManager)
[2021-06-07 13:50:37,019] WARN Either no config or no quorum defined in config, running  in standalone mode (org.apache.zookeeper.server.quorum.QuorumPeerMain)
[2021-06-07 13:50:37,024] INFO Log4j 1.2 jmx support found and enabled. (org.apache.zookeeper.jmx.ManagedUtil)
[2021-06-07 13:50:37,061] INFO Reading configuration from: config/zookeeper.properties (org.apache.zookeeper.server.quorum.QuorumPeerConfig)
[2021-06-07 13:50:37,065] WARN config/zookeeper.properties is relative. Prepend ./ to indicate that you're sure! (org.apache.zookeeper.server.quorum.QuorumPeerConfig)
[2021-06-07 13:50:37,066] INFO clientPortAddress is 0.0.0.0:2181 (org.apache.zookeeper.server.quorum.QuorumPeerConfig)
[2021-06-07 13:50:37,066] INFO secureClientPort is not set (org.apache.zookeeper.server.quorum.QuorumPeerConfig)
[2021-06-07 13:50:37,066] INFO Starting server (org.apache.zookeeper.server.ZooKeeperServerMain)
[2021-06-07 13:50:37,070] INFO zookeeper.snapshot.trust.empty : false (org.apache.zookeeper.server.persistence.FileTxnSnapLog)
[2021-06-07 13:50:37,091] INFO Server environment:zookeeper.version=3.5.9-83df9301aa5c2a5d284a9940177808c01bc35cef, built on 01/06/2021 20:03 GMT (org.apache.zookeeper.server.ZooKeeperServer)
[2021-06-07 13:50:37,091] INFO Server environment:host.name=localhost (org.apache.zookeeper.server.ZooKeeperServer)
[2021-06-07 13:50:37,092] INFO Server environment:java.version=11.0.11 (org.apache.zookeeper.server.ZooKeeperServer)
[2021-06-07 13:50:37,092] INFO Server environment:java.vendor=Ubuntu (org.apache.zookeeper.server.ZooKeeperServer)
[2021-06-07 13:50:37,092] INFO Server environment:java.home=/usr/lib/jvm/java-11-openjdk-amd64 (org.apache.zookeeper.server.ZooKeeperServer)
...
[2021-06-07 13:50:37,093] INFO Server environment:java.library.path=/usr/java/packages/lib:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib (org.apache.zookeeper.server.ZooKeeperServer)
[2021-06-07 13:50:37,093] INFO Server environment:java.io.tmpdir=/tmp (org.apache.zookeeper.server.ZooKeeperServer)
[2021-06-07 13:50:37,093] INFO Server environment:java.compiler=<NA> (org.apache.zookeeper.server.ZooKeeperServer)
[2021-06-07 13:50:37,093] INFO Server environment:os.name=Linux (org.apache.zookeeper.server.ZooKeeperServer)
[2021-06-07 13:50:37,093] INFO Server environment:os.arch=amd64 (org.apache.zookeeper.server.ZooKeeperServer)
[2021-06-07 13:50:37,093] INFO Server environment:os.version=5.4.0-74-generic (org.apache.zookeeper.server.ZooKeeperServer)
[2021-06-07 13:50:37,093] INFO Server environment:user.name=jeffn (org.apache.zookeeper.server.ZooKeeperServer)
[2021-06-07 13:50:37,093] INFO Server environment:user.home=/home/jeffn (org.apache.zookeeper.server.ZooKeeperServer)
[2021-06-07 13:50:37,093] INFO Server environment:user.dir=/home/kafka28/kafka_2.13-2.8.0 (org.apache.zookeeper.server.ZooKeeperServer)
[2021-06-07 13:50:37,094] INFO Server environment:os.memory.free=494MB (org.apache.zookeeper.server.ZooKeeperServer)
[2021-06-07 13:50:37,094] INFO Server environment:os.memory.max=512MB (org.apache.zookeeper.server.ZooKeeperServer)
[2021-06-07 13:50:37,094] INFO Server environment:os.memory.total=512MB (org.apache.zookeeper.server.ZooKeeperServer)
[2021-06-07 13:50:37,095] INFO minSessionTimeout set to 6000 (org.apache.zookeeper.server.ZooKeeperServer)
[2021-06-07 13:50:37,096] INFO maxSessionTimeout set to 60000 (org.apache.zookeeper.server.ZooKeeperServer)
[2021-06-07 13:50:37,096] INFO Created server with tickTime 3000 minSessionTimeout 6000 maxSessionTimeout 60000 datadir /tmp/zookeeper/version-2 snapdir /tmp/zookeeper/version-2 (org.apache.zookeeper.server.ZooKeeperServer)
[2021-06-07 13:50:37,109] INFO Using org.apache.zookeeper.server.NIOServerCnxnFactory as server connection factory (org.apache.zookeeper.server.ServerCnxnFactory)
[2021-06-07 13:50:37,112] INFO Configuring NIO connection handler with 10s sessionless connection timeout, 1 selector thread(s), 4 worker threads, and 64 kB direct buffers. (org.apache.zookeeper.server.NIOServerCnxnFactory)
[2021-06-07 13:50:37,122] INFO binding to port 0.0.0.0/0.0.0.0:2181 (org.apache.zookeeper.server.NIOServerCnxnFactory)
[2021-06-07 13:50:37,142] INFO zookeeper.snapshotSizeFactor = 0.33 (org.apache.zookeeper.server.ZKDatabase)
[2021-06-07 13:50:37,147] INFO Snapshotting: 0x0 to /tmp/zookeeper/version-2/snapshot.0 (org.apache.zookeeper.server.persistence.FileTxnSnapLog)
[2021-06-07 13:50:37,151] INFO Snapshotting: 0x0 to /tmp/zookeeper/version-2/snapshot.0 (org.apache.zookeeper.server.persistence.FileTxnSnapLog)
[2021-06-07 13:50:37,173] INFO PrepRequestProcessor (sid:0) started, reconfigEnabled=false (org.apache.zookeeper.server.PrepRequestProcessor)
[2021-06-07 13:50:37,180] INFO Using checkIntervalMs=60000 maxPerMinute=10000 (org.apache.zookeeper.server.ContainerManager)

[2021-06-07 13:52:53,000] INFO Creating new log file: log.1 (org.apache.zookeeper.server.persistence.FileTxnLog)

and then I was able to launch Kafka. No errors.

2021-06-07 13:52:57,052] INFO [KafkaServer id=0] started (kafka.server.KafkaServer)

**Comment by Sachin-Suresh** [comment]
Great, @JeffreyNovotny, What version of Java were you using in Ubuntu 20.04? What might be the possible issues with my system?

**Comment by JeffreyNovotny** [comment]
> Great, @JeffreyNovotny, What version of Java were you using in Ubuntu 20.04? What might be the possible issues with my system?

Hi @Sachin-Suresh,
I'm using Java 11.0.11.

java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

Did you start from a fresh Ubuntu install or are there other applications on your system that might be conflicting?

Basic process should be (to this point ... I skipped the non-essential steps):
1) Ensure system is updated (apt-get update/upgrade, etc.)
sudo apt update
2) sudo apt install openjdk-11-jdk
3) Check version:  java -version
4) Some combination of untarring the binary and moving it to destination directory:
--  tar -zxvf kafka_2.13-2.8.0.tgz
--  sudo mkdir /home/kafka28
--  sudo mv kafka_2.13-2.8.0 /home/kafka28
5)  cd /home/kafka28/kafka_2.13-2.8.0/
6) bin/zookeeper-server-start.sh config/zookeeper.properties

Were there any errors in your Java install? Perhaps remove Java and reinstall it? That has worked for me before when an app was giving me trouble.

**Review by leslitagordita — APPROVED** [review]

**Review by andystevensname — APPROVED** [review]

**Pull request merged**
