### PR TITLE
[Update] Longview

### PR DESCRIPTION
**Pull request by cwlinode**

### CODE REVIEW

**Comment by GuessWhoSamFoo** [comment]
@cwlinode This needs to be reviewed by multiple people since it's "source" documentation e.g. https://github.com/linode/longview points back here.

**Comment by kcraig34** [comment]
@GuessWhoSamFoo -- Are you recommending this be put into "review" for each team member to look over - or do we need devs involvement? 
@cwlinode, if so, please ask for a review from appropriate personages.
Thanks.

**Comment by cwlinode** [comment]
@kcraig34 It's been looked over by a few people outside of the docs team for specific issues. @GuessWhoSamFoo and I talked it out further, and we're good to go.

**Comment by kcraig34** [comment]
Sounds, good @cwlinode. Putting it into Done and Done. Thanks.

**Pull request merged**
