### PR TITLE
Installing Gogs on Debian Jessie

### PR DESCRIPTION
**Pull request by flowfree**
New guide for installing Gogs, a self-hosted Git service similar with GitLab on Debian 8.

### CODE REVIEW

**Comment by alexfornuto** [comment]
Hey @flowfree I've completed a tech test and made some edits. Please review and merge https://github.com/flowfree/linode-docs/pull/1

**Comment by flowfree** [comment]
@alexfornuto I've merged the pull request.

**Comment by kcraig34** [comment]
Copy edit complete and ready for you to merge: https://github.com/flowfree/linode-docs/pull/2

**Comment by flowfree** [comment]
@kcraig34 I've merged the pull request.

**Comment by alexfornuto** [comment]
@flowfree can you confirm that nashruddin.amin@gmail.com is the correct email for a PayPal payment?

**Comment by alexfornuto** [comment]
Your guide has been published and payment sent! Thanks for your contribution.

**Comment by flowfree** [comment]
Thanks!

**Pull request merged**
