### PR TITLE
[Update] MongoDB Guides

### PR DESCRIPTION
**Pull request by andystevensname**
This is a rebase of https://github.com/linode/docs/pull/2798 . Testing to see if this resolved the merge conflicts found in that branch.

### CODE REVIEW

**Comment by nmelehan** [comment]
Deploy preview for *nostalgic-ptolemy-b01ab8* ready!

Built with commit 5c4d64e0036f921815c3489f230414e8ba053bb5

https://deploy-preview-2894--nostalgic-ptolemy-b01ab8.netlify.com

**Comment by nmelehan** [comment]
Deploy preview for *nostalgic-ptolemy-b01ab8* ready!

Built with commit 4a895f4329011fcff32d26141ee55fbd2b2d7fca

https://deploy-preview-2894--nostalgic-ptolemy-b01ab8.netlify.com

**Comment by andystevensname** [comment]
This PR is ready for review

**Comment by nmelehan** [comment]
Looks like the bulk of the actual changes to the guides got snuck into #2822, and that's already merged into develop. I'll review the title and h1_title changes in this PR

**Pull request merged**
