### PR TITLE
Hotfix v1.67.1

### PR DESCRIPTION
**Pull request by nmelehan**
Theme updates:

- Include sections in Algolia export
    - This commit adds a new isBranch facet to guides/documentation indices
- Netlify: Bump to Hugo 0.83.1
    - This is needed to be able to point this preview to an alternative Algolia host.
-  Add GA event tracking on Explore menu
-  Make sure bold/italic links stays green
-  Fix `published` vs `updated` issue in title byline:
    - Exclude the time when comparing the dates to make sure "published" is printed when applicable.
-  Add structured data
    -  This commits adds structured data to all pages on the docs site.
    -  It will use the schema base from a file named structured-data.json next to the content file, if exists
    -  If not it will fall back to a generic `NewsArticle`
    -  If will add a minimal set of default info if not already in structured-data.json:    [@context](https://github.com/context) ,  [@type](https://github.com/type) , headline, datePublished, dateModified, publisher
- cypress: Log A11y errors
- cypress: Fix shaky test
- Change "Blogs" to "Blog"
- Change aria-label binding on expand/collapse arrow buttons in explore nav
- Added comment policy
- Create a first take on bundles

### CODE REVIEW

**Comment by nmelehan** [comment]
getting this cypress error

```1) Sections
       Filters should limit the number of guides and it should persist on reload:
     AssertionError: Timed out retrying after 4000ms: expected 201 to be within 100..200
      at Context.eval (http://localhost:1313/__cypress/tests?p=cypress/integration/sections.spec.js:150:46)```

**Comment by nmelehan** [comment]
Figured out some issues with how sections are being displayed that relates to the failed cypress test. Will file an issue with bep:

Screen Shot 2021-07-26 at 5 49 16 PM
Screen Shot 2021-07-26 at 5 49 43 PM

**Review by alertmybanjos — APPROVED** [review]
Test-built Algolia... succeeded
Ran cypress tests locally... only one (expected) issue
Click-checked all new features... all appear to be working

**Comment by nmelehan** [comment]
Registered issues here:
https://github.com/linode/linode-docs-theme/issues/108
https://github.com/linode/linode-docs-theme/issues/107

Talked with @alertmybanjos about the impact of these issues, which seems low, and we decided to move forward with release.

**Pull request merged**
