### PR TITLE
Updated document on How to set up a Minecraft server on Ubuntu or Deb…

### PR DESCRIPTION
**Pull request by northcuttmcc**
…ian guide
Updated with SEO recommendations

### CODE REVIEW

**Comment by nmelehan** [comment]
Deploy preview for *nostalgic-ptolemy-b01ab8* ready!

Built with commit 2939dfb2090e2563e37cb7ec79749c34651f4c77

https://deploy-preview-4060--nostalgic-ptolemy-b01ab8.netlify.app

**Comment by Rajakavitha1** [comment]
@northcuttmcc  unable to edit the files for the changes that need to be made. Please add me as a collaborator on the branch.

**Comment by Rajakavitha1** [comment]
A new PR https://github.com/linode/docs/pull/4424 replaces this PR.

**Comment by andystevensname** [comment]
Closed in favor of another PR

**Pull request closed without merging**
