### PR TITLE
[NEW] Nginx Reverse Proxy

### PR DESCRIPTION
**Pull request by mohsenSy**
This tutorial contains information about the following topics:
  * A brief introduction to reverse proxies.
  * Using Nginx as a reverse proxy.
  * Passing request headers to backend servers.
  * Buffering responses and choosing a bind address for the proxy endpoint.

### CODE REVIEW

**Comment by GuessWhoSamFoo** [comment]
Thanks for your submission. You are currently using the old styling. Can you update to meet the syntax from the [formatting guide](https://www.linode.com/docs/linode-writers-formatting-guide/)?

**Comment by mohsenSy** [comment]
@GuessWhoSamFoo I updated to the new style but the same error exists, can you help me please?

**Comment by GuessWhoSamFoo** [comment]
@mohsenSy Thanks for updating

**Comment by Guaris** [comment]
@mohsenSy Hello! Thanks for updating your guide, it's very good. However, would you be able to implement real examples into the guide? It would be nice for a user to access the guide and be able to learn with an example. For instance in your first section, you could add a section about `nginx -t` and curl the localhost to check if it's working. 

You don't have to add elasticsearch to make the point you are trying to make, but consider an example url with a "hello world", and it redirecting to an example url with a "hello world #2 " or something like that. 

Keep up the good work.

**Comment by mohsenSy** [comment]
@Guaris Thanks for your comments, I will  start working on them, I need about two days to get it done.

**Comment by mohsenSy** [comment]
@Guaris I made large modification to the tutorial, hope you will like it :smile:

**Comment by GuessWhoSamFoo** [comment]
Closed in favor of #1332

**Pull request closed without merging**
