### PR TITLE
tmux

### PR DESCRIPTION
**Pull request by zerocreativity**

### CODE REVIEW

**Comment by kcraig34** [comment]
Alexandru -

This is a good, thorough tmux guide; but the team is hoping you can trim this down so it resembles more of a Quick Answer guide (https://www.linode.com/docs/quick-answers).
We're hoping that you'll consent to reviewing the QAs and applying that format to the Tmux content you've written. - So, no new writing, just a more focused approach.

Thanks.

Keith

**Comment by zerocreativity** [comment]
You mean like this: https://www.linode.com/docs/networking/ssh/using-gnu-screen-to-manage-persistent-terminal-sessions?

There's no reference to Microsoft Windows in the article, just tmux's windows and panes (assuming that's where the confusion came from).

**Comment by Guaris** [comment]
Alexandru @zerocreativity, sorry for the confusion. The windows reference was a misunderstanding, and I apologize. The GNU-screen guide is a good example to follow. Shoot for brief and informative. Ping me if you need more clarity.

**Comment by zerocreativity** [comment]
@Guaris if you see anything else that can be trimmed down, ping me back.

**Comment by GuessWhoSamFoo** [comment]
Closed in favor of #1279

**Pull request closed without merging**
