### PR TITLE
Add guide for enabling 2-factor authentication for SSH with a YubiKey

### PR DESCRIPTION
**Pull request by huw**
A [YubiKey](https://www.yubico.com/products/yubikey-hardware/yubikey4/), in case you're unfamiliar with it, is a device that simulates a hardware keyboard to automatically type OTPs and 2FA codes (as well as static passwords) for authentication purposes.

This guide details a really handy way to log into a Linode via SSH with 2-factor authentication, or have the YubiKey be the single factor. This guide is an alternative to linode/docs#434 for users who have YubiKeys and don't want a GPG-based system.

### CODE REVIEW

**Comment by alexfornuto** [comment]
@huw where does this guide fall into place alongside your previous Pull Request? Do they compliment each other, or is it more of an either/or case, in terms of which you could follow?

**Comment by huw** [comment]
The first guide (GPG) is a more general case, which works for anyone with a Linode and GPG key. It includes a small section on moving those GPG keys to a YubiKey in case the reader has one and would like to use the system that way.

This guide is specifically for people with YubiKeys and Linodes, and doesn't use GPG keys.

So, if you don't have a YubiKey, you have one option—the first guide. If you have one, then it's an either/or. I suppose the guides complement each other somewhat, then?

(Thanks for getting back to me on this 😄 )

**Comment by huw** [comment]
I don't mean to bug, but is anything happening with this?

**Comment by alexfornuto** [comment]
@huw It's going to be reviewed once we get to it in the PR list. There are still another 5 or so PRs before yours to sort out.

**Comment by alexfornuto** [comment]
Hey @huw, I just wanted to give you another update. I'm the guy on the team with a yubikey (which is why I tested your other guide on GPG keys for ssh), so I have to be the tester for this guide. But I'm also the manager of the team, so my time is split pretty heavily. Rest assured, this guide will be the next one I pick up.

**Comment by pbzona** [comment]
Hi @huw,

I realize it's been a while since you heard from us, but I want to let you know what's going on. Alex is no longer with us, and with him being the only one with a Yubikey, we've unable to test this. We're still very much interested in publishing your guide, but we'll need to find someone with the proper equipment so we can run through your instructions to make sure everything works as expected. Thanks for your patience, I'll see what I can do about moving this along since this is one of our oldest PRs.

**Comment by alexfornuto** [comment]
"No longer with us" sounds so grim. Don't worry, I'm still alive!

**Comment by huw** [comment]
Thanks guys! Best of luck with moving it on—I'm still watching :)

**Comment by gesellix** [comment]
@pbzona If you like, I could give it a try or would you need someone from the Linode team to test the guide?

**Comment by gesellix** [comment]
>  pbzona was unassigned by gesellix 17 seconds ago

🤔

**Comment by alexfornuto** [comment]
@pbzona is also "no longer with us". He's with me, on... *the island*.

**Comment by pbzona** [comment]
Whoops, thought I had unassigned myself from everything before I sailed off into the sunset. Sorry for the confusion!

**Comment by gesellix** [comment]
No problem, I'll check the tutorial as time permits and leave note here.

**Comment by GuessWhoSamFoo** [comment]
@huw I'm planning to pick this back up. The team ordered a Yubikey to verify instructions in the guide. Keep posted next week for updates!

**Comment by huw** [comment]
Thank you very much! AFAIK the guide doesn't need updating, but since I imagine you've ordered a YubiKey 4, let me know if anything's different.

**Comment by GuessWhoSamFoo** [comment]
Closed. Refer to new PR for edits.

**Pull request closed without merging**
