### PR TITLE
Update run-a-distribution-supplied-kernel-with-kvm.md

### PR DESCRIPTION
**Pull request by KFDCompiled**
Added lines for Gentoo

### CODE REVIEW

**Comment by alexfornuto** [comment]
Thanks for the addition, but this is incomplete. No kernel, nothing in `/boot/` running these directions only.

**Comment by alexfornuto** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;CijX6XNI&#x2F;1-update-distribution-supplied-kernel-guide-for-gentoo-bounty-update"> Update Distribution Supplied Kernel guide for Gentoo | Bounty, update</a>

**Comment by KFDCompiled** [comment]
Can you add me to the trello board so I can collect the Bounty? I'm not
sure what wasn't correct on my pull request as you can see I'm running
gentoo w/ custom kernel on my linode.

Thanks,
Kent

**Comment by alexfornuto** [comment]
@KFDCompiled Please take a loot at https://github.com/KFDCompiled/docs/pull/1

**Comment by alexfornuto** [comment]
Thanks for the addition @KFDCompiled!

**Pull request merged**
