### PR TITLE
[NEW]Deploy AskBot on Ubuntu 16.04

### PR DESCRIPTION
**Pull request by gopalraha**
How to Install and Deploy Askbot Question and Answer Forum with LetsEncrypt SSL on Ubuntu 16.04

### CODE REVIEW

**Comment by gopalraha** [comment]
Please merge all **upload** files on file **Deploy AskBot on Ubuntu 16.04**

**Comment by cwlinode** [comment]
@gopalraha Hi, thanks for your submission, but I'm not able to get it working as it's written. 

Gunicorn and nginx are both running according to systemd, but Gunicorn is not listening according to ss, and going to the Linode's IP in a web browser just shows an Example Domain page.

**Comment by gopalraha** [comment]
Hi, @cwlinode 

Gunicorn is not a service it is act as a daemon with systemd `sudo systemctl daemon-reload`

Most important thing is this tutorial works with only with domain name like `example.com` OR `www.example.com` and IP address is redirecting to domain name that`s our nginx configuration.

Please tell what your **testing** `example_username` and **testing** `domain name`. I have to modify the tutorial according to your **testing** `username` and **testing** `domain name`.

In which step you have facing this type of issues please tell I shall help you to rectify that issue.

**Comment by cwlinode** [comment]
Hi @gopalraha,
The rm command was run on all three locations as your guide instructs, as was the systemd reload.

The user name used was 'example_user', and no bought domain was used. Rather, example.com was mapped to the Linode's IP address in /etc/hosts. This shouldn't be necessary, but was done as a last precaution and still no luck.

**Comment by gopalraha** [comment]
Hi @cwlinode ,

**No need to edit the host file** `/etc/hosts` **keep it as it is**. This guide deals with Letsencrypt SSL so it requires a valid domain name to get SSL certificates. 

I have tested the above docs a hour ago with username `example_user` and domain name `techbrown.net` and `www.techbrown.net` and domains names are pointed to my Linode . It was running on my 1GB Linode with IP `45.79.190.143` .

You can visit `https://techbrown.net` OR `https://www.tehbrown.net` for live demo of Askbot. You can create first user that will be admin user of AskBot Q&A Forum.

If you want my 1GB Linode password please mail me.. You can check my Linode instances.

If possible please recheck your Linode instances with all the steps above..

Thanks and Regards :)

**Comment by gopalraha** [comment]
Hi @cwlinode ,

I have created a video tutorial for above guide. But before starting video I have done these steps:

1. Username is `example_user` with **sudo privileges**
2. The Domain name is `techbrown.net` and `www.techbrown.net` and pointed towards Linode IP using `DNS Manager`

I have created a Private Video that can be opened only with password:

Video URL:  `https://vimeo.com/232243699`
Video Password: `askbotpass`

You can check the video tutorial if issue persist you can reply....

**Comment by cwlinode** [comment]
@gopalraha Thanks, that was helpful.

**Pull request merged**
