### PR TITLE
Murmur on Debian

### PR DESCRIPTION
**Pull request by markzz**

### CODE REVIEW

**Comment by alexfornuto** [comment]
@markzz did you mean to close this PR?

**Comment by markzz** [comment]
Yes, it was sitting there for ages and I'm cleaning up my GitHub account of stuff that either is ignored or unimportant.

**Comment by alexfornuto** [comment]
I'm really sorry that we missed this. You should have received an acknowledgement within a week or two of submission. If you're still interested in the submission, @thetechstewart will take a look at it now.

**Comment by alexfornuto** [comment]
We just published a guide on TeamSpeak, so I'd be interested in having an alternative to go along with it.

**Comment by markzz** [comment]
I have already deleted the repository that had it and this prevents me from reopening the the request anyways.

**Comment by alexfornuto** [comment]
Well the guide and images are still visible from the PR, so we could make a new PR ourselves (as could you) if you're still interested in submitting it for the bounty. If not, I understand. Again, I apologize for the oversight.

**Comment by markzz** [comment]
Resubmitted in #261.

**Pull request closed without merging**
