### PR TITLE
Control Network Traffic With FirewallD

### PR DESCRIPTION
**Pull request by thetechstewart**
This is an import from a submission given to us via email. It has not yet been reviewed for technical accuracy or edited for for proper formatting. It's purpose here is to gauge interest from the community on this subject, and solicit independent review of the contents.

### CODE REVIEW

**Comment by fhoubart** [comment]
Hi,

I have read the last edit, and found some missing quotes in the `--add-rich-rule` parameters:

line 248:

    firewall-cmd --zone=public --add-rich-rule rule family="ipv4" source address="192.168.2.2" accept
    Should be:
    firewall-cmd --zone=public --add-rich-rule 'rule family="ipv4" source address="192.168.2.2" accept'

line 252:

    firewall-cmd --zone=public --add-rich-rule rule family="ipv4" source address="192.168.1.10" port port=22 protocol=tcp reject
    Should be:
    firewall-cmd --zone=public --add-rich-rule 'rule family="ipv4" source address="192.168.1.10" port port=22 protocol=tcp reject'

line 256:

    firewall-cmd --zone=public --add-rich-rule rule family=ipv4 source address=10.1.0.3 forward-port port=80 protocol=tcp to-port=6532
    Should be:
    firewall-cmd --zone=public --add-rich-rule 'rule family=ipv4 source address=10.1.0.3 forward-port port=80 protocol=tcp to-port=6532'

line 268:

    firewall-cmd --zone=public --add-rich-rule rule family=ipv4 forward-port port=80 protocol=tcp to-port=8080 to-addr=172.31.4.2
    Should be:
    firewall-cmd --zone=public --add-rich-rule 'rule family=ipv4 forward-port port=80 protocol=tcp to-port=8080 to-addr=172.31.4.2'

And I see the bash prompt has been removed everywhere. I find it confusing, because we cannot distinguish the typed command and the command output. Maybe we should keep at least the `#` prompt? Example:

    # firewall-cmd --state  <-- this is the typed command
    running    <-- this is the standard output

**Comment by thetechstewart** [comment]
@thoubart:  Thanks for the comments.  I'll look into those missing quotes and make sure they get added correctly.  As for the command prompt, our guides generally do not include it, and we generally separate commands and output from each other.  This enables readers to directly copy and paste lines from guides without having to remove the prompt markers.  We will address separation of the commands and output during our copy edit phase.

**Comment by thetechstewart** [comment]
@fhoubart - We've completed the final copy edit on your guide, could you review the final version of the guide (https://github.com/thetechstewart/docs/blob/99b72e386266969b312ce915706ae81da8f23920/docs/security/firewalls/control-network-traffic-with-firewalld.md) and let us know whether you approve us publishing the final version?

**Comment by fhoubart** [comment]
Hi,
First, sorry for this late answer. The final version is nice, there is just a few quotes missing in *Rich Rules* paragraph. The first snippet of command is fine, the 3 next ones are missing single quotes for the argument following *--add-rich-rule*: 

    sudo firewall-cmd --zone=public --add-rich-rule 'rule family="ipv4" source address="192.168.1.10" port port=22 protocol=tcp reject'

    sudo firewall-cmd --zone=public --add-rich-rule 'rule family=ipv4 source address=10.1.0.3 forward-port port=80 protocol=tcp to-port=6532'

    sudo firewall-cmd --zone=public --add-rich-rule 'rule family=ipv4 forward-port port=80 protocol=tcp to-port=8080 to-addr=172.31.4.2'

**Comment by cwlinode** [comment]
@fhoubart - Single quotes added. Thanks for that.

**Pull request merged**
