### PR TITLE
[TECH] Multiple wordpress on one Linode

### PR DESCRIPTION
**Pull request by GuessWhoSamFoo**
- Deprecated older identical guide - pending delete: https://www.linode.com/docs/websites/cms/how-to-install-and-configure-wordpress
 - Fixed root directory wording on older WordPress guide: https://www.linode.com/docs/websites/cms/install-wordpress-on-ubuntu-16-04
 - Explicitly show example for a two Wordpress setup

### CODE REVIEW

**Comment by GuessWhoSamFoo** [comment]
[Running Multiple Wordpress Sites on One Linode - Bounty, J. TSai (Oct.)](https://trello.com/c/pE0c7QbS/78-running-multiple-wordpress-sites-on-one-linode-bounty-j-tsai-oct)

**Comment by GuessWhoSamFoo** [comment]
@jontsai The guide did mention setting up a LEMP stack but only provided an Apache configuration. Do you want to provide an nginx config as well or just limit the scope to LAMP?

**Comment by GuessWhoSamFoo** [comment]
@EdwardAngert Let's just move forward with this. If there are plans to add LEMP in the future, we can do so.

@kcraig34 This needs an SEO edit

**Comment by kcraig34** [comment]
I believe this guide has had both a CE and SEO performed.
@EdwardAngert:  Can you verify? If they're done, we only need an image and SMPs.
Thanks...

**Pull request merged**
