### PR TITLE
Don't Starve Together on Ubuntu 14.04

### PR DESCRIPTION
**Pull request by agottschling**

### CODE REVIEW

**Comment by ellekrout** [comment]
Hey Andrew!

While tech testing your guide, I came across an issue with with step three: While first loading the server, instead of launching successfully, it fails to load. The output is kind of long, so I put it in a gist here: https://gist.github.com/ellekrout/ceb5e8d3222a6fd6c89c

Any ideas of what the issue could be?

Thanks!

**Comment by agottschling** [comment]
Hey Elle,
This issue is normal. You don't have a valid server token, which you get from owning the game, and the server will not load to anything except LAN mode. Continuing with the process and adding a valid server token will get rid of this error.

**Comment by agottschling** [comment]
do you need a valid server token? If so, I have a development VPS that I use for tech testing , which happens to have my server token on it. If you need access, let me know and I can create a account for you.

**Comment by ellekrout** [comment]
I got it to work. I was mostly concerned about the output "your server will not start" error. Thank you for addressing it.

I'm going to send a PR against your guide with everything reformatted into our markdown format. If everything with that looks okay, we can move on and have your guide copy edited.

Thank you!

**Comment by agottschling** [comment]
alright. I merged your pull request. You may just want to check it over to make sure I did it right.

**Comment by alexfornuto** [comment]
@agottschling When you merged @ellekrout's changes there were conflicts, which were not resolved. The file now has several references like this `<<<<<<< HEAD` and `>>>>>>> ed992cf6f64253f1e70854fb049135ce57dea609`. Please resolve the merge conflicts so that we can proceed.

**Comment by agottschling** [comment]
I've taken care of everything. Might just want to make sure that I didn't break any formatting.

**Comment by agottschling** [comment]
Thanks for the guide. Never really used Github before.

**Comment by alexfornuto** [comment]
@agottschling I've created https://github.com/agottschling/docs/pull/2 which is my copy edit for this guide. As denoted in that PR, it is a pretty heavy-handed edit, but I'm willing to explain any questions you have on my proposed changes.

**Comment by agottschling** [comment]
pull request merged. Should be good from here.

**Comment by alexfornuto** [comment]
Great! I'm going to have one more person on my team give it a once over, since I made so many changes. We should have this out the door by mid next week.

**Comment by agottschling** [comment]
Pull Request Merged

**Comment by agottschling** [comment]
do you need my paypal details?

------ Original Message ------

**Comment by ellekrout** [comment]
Yes! If you would understandably rather not post them here, please email us your information and we'll get you paid.

Thank you!

**Comment by agottschling** [comment]
I am sending you guys an email right now. Do you just need the email address, or is other information required?

**Comment by ellekrout** [comment]
The your paypal email should be fine.

**Comment by alexfornuto** [comment]
@agottschling Thanks so much for this guide! It was a lot of fun to test, and I will probably keep my own persistent game running from now on.

**Pull request merged**
