### PR TITLE
Deploying a LAMP stack fast and easily with Ansible

### PR DESCRIPTION
**Pull request by rbbrasil**
Hello guys,

Here is my article about Ansible.

### CODE REVIEW

**Comment by ellekrout** [comment]
Hi @rbbrasil!

Just letting you know that I will be completing a technical test with regards to this article soon, and you should hear back within a week with any comments or changes that should be made.

Thank you for your patience!

**Comment by rbbrasil** [comment]
No problem, @ellekrout 

Thanks for the feedback!

**Comment by ellekrout** [comment]
Hello again!

I have a question before I continue testing the guide: Initially it's presented as being created for Debian 8, but when it comes to deploying the actual playbook, things switch over to Red Hat distros. Is there a reason for this switch? It would be more cohesive if one distro was chosen or the guide included instructions for both.

Just want to get this cleared up before we proceed. Thank you!

**Comment by rbbrasil** [comment]
Actually, it's written for Debian client (line 7) and CentOS/RedHat target host (line 68). If you think that could cause some confusion, I can change the commands/instructions and work only with one type of distro.

I just wrote that way to show that Ansible playbooks has no limitations when running between distributions of different families on the client x server side.

**Comment by ellekrout** [comment]
Ah! Yes, there is some confusion there, but I think if it is defined in the opening paragraphs that we're working with a Debian client and CentOS/RH target host, we'll be good to go.

**Comment by rbbrasil** [comment]
Hi @ellekrout !

Is there any other considerations on this article?

**Comment by thetechstewart** [comment]
@rbbrasil:  Unfortunately, after a great deal of consideration, we were unable to accept this guide for inclusion in the Linode Guides and Tutorials.  We do appreciate your submission, and we encourage you to reach out again if you'd like to submit articles on any other topics.

**Comment by rbbrasil** [comment]
@thetechstewart, could you explain me the reasons? It had been in analysis for more than 20 days and I would be pleased to know why, just in case I decide to submit another one.

**Pull request closed without merging**
