### PR TITLE
Icinga2 Final

### PR DESCRIPTION
**Pull request by caezsar**

### CODE REVIEW

**Comment by Guaris** [comment]
@caezsar Hey, what is different in the final draft of your guide? Are there critical changes? I’m asking because this guide was submitted 25 days ago, and has since been edited and tested. I was not aware that you would be submitting another version. 

I appreciate your thoroughness, but in the future, please understand that once a guide is accepted into our review process no more revisions should be made unless someone reaches out to you.

**Comment by caezsar** [comment]
Sorry for bad inconvenient, wasn' t aware of this. I've reviewed the guide and removed some unneeded instructions and screenshots.one of the collaborators suggested   that i should move pics in a new directory under assets.I thought that it can be modified before publishing date.

**Comment by Guaris** [comment]
I see. No worries, those were instructions that I had left for another person on the team. Sorry for the confusion. Your guide is well on its way to being published. 👍

**Comment by GuessWhoSamFoo** [comment]
Duplicate of #1287

**Pull request closed without merging**
