### PR TITLE
Just Cause 2 Multiplayer Server on Ubuntu 14.04

### PR DESCRIPTION
**Pull request by agottschling**
New tutorial submission: Just Cause 2 Multiplayer Mod Server setup.

### CODE REVIEW

**Comment by agottschling** [comment]
@thetechstewart Any idea when this will be moved into a copy edit?

**Comment by ellekrout** [comment]
Hi @agottschling! This actually moved into copy edit today!

**Comment by agottschling** [comment]
Pull Request Merged.

**Comment by agottschling** [comment]
@ellekrout I merged the pull request from @kcraig34 
Should be good to go on my end

**Comment by agottschling** [comment]
@kcraig34 @ellekrout Pull request merged. Should be good to go from here

**Comment by ellekrout** [comment]
Hello @agottschling!

We've got this published and live here:  https://linode.com/docs/applications/game-servers/just-cause-2-multiplayer-on-ubuntu

However, before we process payment I just wanted to make sure your PayPal email hasn't changed since last time--better be safe and ask before sending money into the ether. Let me know either way, so I can get you paid! Thanks so much.

**Comment by agottschling** [comment]
@ellekrout It hasn't changed. Should still be andrewgottschlingATgmxDOTus

**Comment by ellekrout** [comment]
@agottschling Awesome! Passing your info to our billing department now!

**Comment by agottschling** [comment]
CRAP! Just realized I left something in the guide. Where it says "Install SteamCMD and Don't Starve Together" It should say "Install SteamCMD and Just Cause 2" It should be the third heading

**Comment by agottschling** [comment]
Do you want me to open a new pull, or can you just update it?

**Comment by ellekrout** [comment]
I'll update, no worries.

**Comment by agottschling** [comment]
@ellekrout Thanks.

**Comment by ellekrout** [comment]
Just pushed the changes, should be live in five to ten minutes with the update. Thanks for catching that!

**Comment by agottschling** [comment]
@ellekrout Thanks for everything. I look forward to writing again for you guys soon.

**Pull request merged**
