### PR TITLE
Left4dead 2 Game Server setup guide 

### PR DESCRIPTION
**Pull request by agottschling**
Linode Game Server Bounty tutorial. How to Install and Configure Left 4 Dead Dedicated server.

### CODE REVIEW

**Comment by agottschling** [comment]
Excuse my goof. I accidentally added a commit that was already pushed and merged. Should be fixed now though.

**Comment by alexfornuto** [comment]
In light of how many guides we're getting regarding Steam game servers, we're looking into making a guide on installing the Steamcli and base system. Once we do we'll revisit guides like this and see how many steps remain.

**Comment by agottschling** [comment]
@alexfornuto If you give me a few hours, I can have a basic guide done on how to install SteamCMD. However, the configuration of the servers, especially Valve's own games, can be quite complex.

**Comment by seanthewebber** [comment]
Andrew makes a good point here. Each Steam game server has it's own quirks and specialties that make it unlike any other server, requiring a slightly different configuration. Writing a prerequisite guide outlining how to install SteamCMD will save future keystrokes, but I wouldn't go any further than that to avoid conflicts.

**Comment by agottschling** [comment]
@thetechstewart any updates on this guide?

**Comment by thetechstewart** [comment]
@agottschling - I've run through your guide and attempted to test connecting to the dedicated server.  However, even after utilizing the in-game console to specify the dedicated server IP address, it's unable to connect.  I've tested this both with firewall rules in place, and with the firewall completely disabled.  I've also modified the startup command as per Steam's own documentation as the command included in your original submission did not execute, and submitted a pull request against your branch reflecting that.  If you could review and pull in that change, and then test for any additional changes that are required to connect to the game server, we can proceed with additional tech testing on our end.

**Comment by davidebeatrici** [comment]
I'm actually using a Left 4 Dead 2 Dedicated Server with my friends, we use different ways to connect to it.
To make things easier, we downloaded a [Workshop Addon](https://steamcommunity.com/sharedfiles/filedetails/?id=214945910) to have a "Console" button in the main menu and [another one](https://steamcommunity.com/sharedfiles/filedetails/?id=121088946) to have a "Server Browser" button.

To connect to the server, you have three ways:
    
1. Open the console and enter this command "connect 12.34.56.78:27015", where 12.34.56.78 is   your IP and 27015 the port.
    
2. Open the server browser and add your server in the favorites by adding its IP and port.

3. Open the server browser and find your server in the (very long) "custom" list.

Advices/Corrections about your guide:

1. It is not needed to have a Steam account nor a game copy to run the dedicated server.

2. Why did you write "This script, when run, will execute the Don't Starve Together server in a Screen session." and "chmod +x ~/dstserver/bin/start_dst.sh"? I think that you took some parts from [your Don't Starve Together Dedicated Server guide](https://www.linode.com/docs/applications/game-servers/dont-starve-together-on-ubuntu) and you didn't remember to change the names :smile:

**Comment by agottschling** [comment]
@davidebeatrici Guilty as charged. It's fixed now. And thanks for the recommendation for the workshop addon. I'll update my guide to reflect that.

**Comment by davidebeatrici** [comment]
You're welcome :smile:

**Comment by agottschling** [comment]
@davidebeatrici that's fair.  I'll update that.

**Comment by agottschling** [comment]
Alright. @davidebeatrici, I think I've fixed everything. Let me know if I missed something. @thetechstewart, I think I've fixed the joining issue. Try it and let me know.

**Comment by davidebeatrici** [comment]
You've fixed everything, but: 
1. You should remove the **port** parameter from the startup command or specify that is not needed, as I said in my advices/corrections list.
2. You should specify that the server will appear only in the **custom** list and that is recommended to add it to the favorites with the IP address and the port to avoid the search.
:wink:

**Comment by agottschling** [comment]
@davidebeatrici Will do.

**Comment by davidebeatrici** [comment]
You fixed everything I said. I read your updated guide and the only thing I noticed that needs to be corrected is in the requisites. I wrote the details in my advices/corrections comment :wink:

**Comment by agottschling** [comment]
@davidebeatrici I have no idea if it works on Debian. However, I don't have a free machine that I can install Debian on. If you want to try it and report back, be my guest.

**Comment by davidebeatrici** [comment]
I already have Left 4 Dead 2 Dedicated Server on my Debian Linode, it works without problems :wink:

**Comment by thetechstewart** [comment]
@agottschling: I've completed tech testing on this guide with both Debian and Ubuntu, the instructions listed do work for both.  I'll review the new changes for accuracy, and change the title to reflect the fact that it works on both platforms, and then I'll pass it on to another member of my team for copy editing.

**Comment by agottschling** [comment]
@thetechstewart thanks.

**Comment by thetechstewart** [comment]
@agottschling: I've made a PR against your branch with my tech testing adjustments.  Once you have accepted that PR, I'll pass this on to another member of my team for copy editing.

Thanks!

**Comment by agottschling** [comment]
Just merged.  Ready for the next steps

**Comment by agottschling** [comment]
@thetechstewart I merged your pull. It should be ready for a copy edit.

**Comment by agottschling** [comment]
Merged copy edit pull request. Ready for the next steps.

**Comment by agottschling** [comment]
@thetechstewart Any further things I need to do?

**Comment by agottschling** [comment]
@thetechstewart I merged the pull request from @kcraig34. Anything else I need to do?

**Comment by agottschling** [comment]
Note merged.

**Comment by agottschling** [comment]
@thetechstewart anything else I need to do moving forward?

**Comment by agottschling** [comment]
@cwlinode Just in case you still need my PayPal address, it's andrewgottschlingATgmxDOTus

**Comment by cwlinode** [comment]
@agottschling Thank you for your contribution. Your article has been published:
https://www.linode.com/docs/applications/game-servers/left-4-dead-2-multiplayer-server-installation

You should receive payment within 24 hours at the address you gave above.

**Pull request merged**
