### PR TITLE
Guide for Configuring Nagios on Debian 10 and Ubuntu 20.04

### PR DESCRIPTION
**Pull request by nasanos**
Submitting a guide for configuring email and IRC alerts from Nagios on Debian 10 and Ubuntu 20.04.

### CODE REVIEW

**Comment by nmelehan** [comment]
Deploy preview for *nostalgic-ptolemy-b01ab8* ready!

Built with commit 20391b1b71ad34238a355e3ec34d54d124ddac64

https://deploy-preview-3944--nostalgic-ptolemy-b01ab8.netlify.app

**Comment by Sachin-Suresh** [comment]
Hi @nasanos, The [NagIRCBot release page ](https://www.vanheusden.com/nagircbot/) seems to be a 404.
Is there any other way we can execute the below command:

`sudo wget http://www.vanheusden.com/nagircbot/nagircbot-0.0.33.tgz`

**Comment by nasanos** [comment]
@Sachin-Suresh Well, there is a version hosted on Nagios' Exchange website, [here](https://exchange.nagios.org/directory/Addons/Notifications/IRC/nagircbot/details). It's an older version — **0.0.16** vs. **0.0.33** — and I don't know if that will impact the implementation described in the guide. But otherwise I expect this version should still have the features we use in the guide.

There is also an Ubuntu Man Page for the NagIRCBot, [here](https://manpages.ubuntu.com/manpages/trusty/man1/nagircbot.1.html), which links to a set of downloadable packages — just follow "Provided by" -> "Source package", and then look in the  "Downloads" section. You can find the page for NagIRCBot version **0.0.33** [here](https://launchpad.net/ubuntu/+source/nagircbot/0.0.33-2). It has an `nagircbot_0.0.33.orig.tar.gz` that looks to what we need.

**Comment by Sachin-Suresh** [comment]
Sure, thanks @nasanos, Let me use `wget` to download the tar and follow the guide thereafter. I will check what changes need to be done in the guide and update you.

**Review by leslitagordita — APPROVED** [review]

**Pull request merged**
