### PR TITLE
Add how to restore into a different data center

### PR DESCRIPTION
**Pull request by wesgarrison**
Asked support about this after trying to find it in this document and this is how they said to do it.

### CODE REVIEW

**Comment by alexfornuto** [comment]
Cool addition. I wonder though, would it make sense if they're making a new Linode to restore to, to just have them migrate the new Linode to said data center?

**Comment by wesgarrison** [comment]
This is how support explained it, so if that's a possibility, I don't know
how to do it.

**Comment by pbzona** [comment]
Hey @wesgarrison, thanks for your patience. This is a good suggestion, I just want to make some tweaks to the formatting and get a second set of eyes from support. I'll get back to you shortly on how we're going to incorporate this.

**Comment by pbzona** [comment]
@wesgarrison After speaking with support, we've modified your instructions just a bit. I'm going to merge them in PR #https://github.com/linode/docs/pull/632, which includes your commit so you'll receive contribution credit. Thanks for this suggestion, and please feel free to let us know if you see more opportunities to improve our documentation.

**Pull request merged**
