### PR TITLE
Bundle conversion - DO NOT MERGE

### PR DESCRIPTION
**Pull request by Jskobos**

### CODE REVIEW

**Comment by Jskobos** [comment]
Sending up the Bat Signal on this one @GuessWhoSamFoo. What's weird here?

**Comment by Guaris** [comment]
merging

**Comment by Guaris** [comment]
j/k

**Comment by Jskobos** [comment]
From here (assuming nothing is broken that I can't see) we still have to manually check ~245 cases where /docs/assets/ is still referred to from within guides. Most of these are shell scripts, config files, and occurrences within wget commands. Also a few images that broke the script and were skipped.

**Comment by GuessWhoSamFoo** [comment]
@Jskobos 
- Duplicate assets in `/docs/assets/` needs to be addressed. Unused assets should be removed (otherwise there is little gained here imo). Even better if style guides addressed naming conventions in assets and write a few checks to enforce.

- IMAGE_LINK_REGEX (https://github.com/Jskobos/docs/blob/master/ci/blueberry.py#L37) needs to handle *.gif in matching

- Consider removing the `image` front matter var. It's linked to https://linode.com/docs/assets/*

- Some shortguides were duplicated (e.g. development/python/index.md  development/ror/index.md etc). Definitely should not have `_index.md` and `index.md` in the same directory

- Would be nice to have the decision making process documented in #1792 - Linode docs is on the Hugo showcase and any sufficiently large site will run into a similar issue.

**Pull request merged**
