### PR TITLE
Guide for MySQL Workbench

### PR DESCRIPTION
**Pull request by scottinthebooth**
This pull request should have a guide in the databases/workbench folder on how to use MySQL Workbench for standard MySQL tasks (user management, creating databases, executing SQL queries, adding new data and tables)

### CODE REVIEW

**Comment by ellekrout** [comment]
Heya @scottinthebooth! Just wanted to touch base:

I was testing this on Fedora and noticed some differences in the Settings layout between this and the Ubuntu version. Because of this, I want to test it on a few other distros (OSX, Windows -- since we have Debian- and Fedora-based systems covered). The differences are fairly small and easy to note, but I won't be done the tech test until next week. I just wanted to keep you in the loop. :)

**Comment by scottinthebooth** [comment]
Yeah, I guess 'tis the nature of cross-platform development

Scott

**Comment by scottinthebooth** [comment]
Thanks for keeping me in the loop, looking forward to your feedback!

**Comment by scottinthebooth** [comment]
Just wanted to see how this was going?  I've got a Linode on the LINODE10 code so I'd love to get credit put on it before it runs out!

**Comment by ellekrout** [comment]
Hey @scottinthebooth! Finally got a PR in for you. Just one small change about the locale of an option of non-Debian distros, but otherwise we're good. I'll get this prioritized for copy edit as soon as you approve the change!

**Comment by ellekrout** [comment]
Hello again! You have a PR of the copy edit waiting for you. Once you approve, we can get this out today, hopefully. If you want to let me know how you want to be paid, as well, we should be good.

**Comment by scottinthebooth** [comment]
Awesome!  I'll check out the PR now.  So question on payment -- can I do
half Linode credit and half PayPal?

Thanks,
Scott

**Comment by ellekrout** [comment]
Yup, no problem!

**Comment by cwlinode** [comment]
@scottinthebooth Please merge ellekrout's PR so we can get you published and paid.

**Comment by scottinthebooth** [comment]
Merged, did it come through OK?  Still figuring out git...

Scott

**Pull request merged**
