### PR TITLE
[Update] DNS Manager UI Updates Jan 2021

### PR DESCRIPTION
**Pull request by rsyracuse**

### CODE REVIEW

**Comment by nmelehan** [comment]
Deploy preview for *nostalgic-ptolemy-b01ab8* ready!

Built with commit 97e449c44f1c70f2beccfe6301369904291b867f

https://deploy-preview-3975--nostalgic-ptolemy-b01ab8.netlify.app

**Review by Rajakavitha1 — CHANGES_REQUESTED** [review]
Not sure if this guides need to be updated for the UI changes:
- docs/products/compute/kubernetes/guides/recycle-node-pool/index.md
- docs/products/compute/kubernetes/guides/upgrade-lke-cluster/index.md

**Review by Rajakavitha1 — APPROVED** [review]

**Review by Rajakavitha1 — CHANGES_REQUESTED** [review]
please remove the files not related to the CMR updates

**Comment by Rajakavitha1** [comment]
@rsyracuse  could you please make the changes because I am not able to push the changes to your branch.

**Comment by wildmanonline** [comment]
These changes are already live so closing this PR.

**Pull request closed without merging**
