### PR TITLE
Added Tutorial for simple Virtual Host creation

### PR DESCRIPTION
**Pull request by sixdev**

### CODE REVIEW

**Comment by sixdev** [comment]
what does open for discussion mean in this case?

**Comment by sixdev** [comment]
And just for your info I have written that script I have not copied it from somewhere else.

**Comment by thetechstewart** [comment]
@sixdev: Once a guide has been submitted, we allow our community to comment on it for a period of 1-2 weeks.  This allows us to gauge a guide's value prior to proceeding with the tech test process.  We will follow up once we've moved on to the next steps.

**Comment by thetechstewart** [comment]
@sixdev: After consideration by our team, we have determined that we will not be able to accept this guide into the Linode Guides and Tutorials.  Our guides are generally formulated for accomplishing larger tasks, such as deploying a specific software stack.  A guide on deploying a specific type of script would not meet our general guidelines for acceptance.

Thank you again for your submission.

**Pull request closed without merging**
