### PR TITLE
[NEW] Install Minecraft inside FreeBSD Container

### PR DESCRIPTION
**Pull request by GuessWhoSamFoo**
XR #1262 

TODO:

- [x] Break apart numbering
- [ ] Change to meet writing style of current docs

### CODE REVIEW

**Comment by GuessWhoSamFoo** [comment]
@RainbowHackerHorse So it looks like the current version of `iocage` has a broken installation on FreeBSD 11.1 (See https://github.com/iocage/iocage/issues/421). Did you end up compiling iocage back when this was written?

**Comment by RainbowHackerHorse** [comment]
@GuessWhoSamFoo I wrote this back when `iocage-legacy` was still the version of `iocage` being utilized.
It looks like everything should be back to normal with `py-iocage` now, but tbh, I think legacy was deprecated early anyway >.> `py-iocage` isn't production ready, as is shown here.
One can use the package from the following link:
[https://github.com/RainbowHackerHorse/Stuffnthings/raw/master/legacypkgs/iocage-1.7.6.txz](url)

To install it directly, one can run the following commands:
`pkg install -y ca_root_nss`
`pkg add https://github.com/RainbowHackerHorse/Stuffnthings/raw/master/legacypkgs/iocage-1.7.6.txz`

**Comment by RainbowHackerHorse** [comment]
It actually looks like there's a maintained fork of iocage legacy called `iocell` and its in ports. I'm going to toy with it, and test this guide with it. If it works, I'll pull down the changes you've made, and update it to use `iocell`

**Comment by GuessWhoSamFoo** [comment]
@RainbowHackerHorse Any updates on this?

**Comment by RainbowHackerHorse** [comment]
s/iocage/iocell and you're good.
It's drop-in compatible.
Haven't had a chance to make the edit myself but it's just a quick find/replace-all

**Comment by RainbowHackerHorse** [comment]
Yeah, since you slurped up the branch, it's a bit harder for me to make the edit now :P

**Comment by GuessWhoSamFoo** [comment]
If just substituting, should be fine - I'll take care of it

**Comment by RainbowHackerHorse** [comment]
@GuessWhoSamFoo Aye, it's just substituting the command name itself. Usage is exactly the same :)

**Comment by GuessWhoSamFoo** [comment]
@RainbowHackerHorse Sorry this took a while. Priorities were shifted around.

Anyhow, I'm running into two issues:

1) `iocell` loses connectivity to the outside world. Entering the jail's console will fail `pkg` and pinging anything. From a Google search, it seems to be a common issue with iocage as well. Any leads on this one?

2) I proceed with the rest without the jail. After running `make all-depends-list | cut -c 12- | xargs pkg install -y`, the message below showed up:

screen shot 2018-02-07 at 4 29 01 pm

Is installation of JDK 8 through ports the recommended way?

**Comment by RainbowHackerHorse** [comment]
No worries!
If connectivity fails, you just need to stop the jail ( `iocage stop $jailname`), restart pf if you haven't (`service pf restart`), and start the jail (`iocage start $jailname`)
Once the pf rules have been added, it is imperative that pf is restarted.
That being said, ping is normally disabled from inside a jail, so that shouldn't be used as a metric for network connectivity. If pkg is failing, then try the steps I outlined :)

Installation via pkg is the recommended way for the JDK (which is what that command is doing), and this is a normal message.
We can update the guide to include that information, but I feel most people would be knowledgeable enough to follow the instructions they'd receive here.

**Comment by RainbowHackerHorse** [comment]
Why was this closed? Has it been imported into the docs Library? AFAIK this was still active and pending.

**Comment by Guaris** [comment]
@RainbowHackerHorse Hey! I closed it. The person assigned to work on this is no longer with us and we don't have the bandwidth to tackle this guide.

**Pull request closed without merging**
