### PR TITLE
Update accounts-and-passwords.md

### PR DESCRIPTION
**Pull request by marrie**
I just changed the spelling of one word. I'm not normally that picky but it is in the managing password section. It was just a mis type. I fixed it. Hope that helps.

### CODE REVIEW

**Comment by FelicianoTech** [comment]
Hi thank you for the contribution. In this case, Linode Manager is actually the name of the interface used by customers to manage their account with us (https://manager.linode.com). This is why both the 'L' and 'M' have been capitalized in that sentence.

We greatly appreciate your keen eye and look forward to future contributions. Thank you.

**Comment by alexfornuto** [comment]
Upper or lower case, Manger isn't a word. Thanks!

**Comment by FelicianoTech** [comment]
Ah so close, looked at the wrong change. Thanks @marrie . The capitalization will be separate.

**Comment by marrie** [comment]
Oops. Yeah Can someone change that little oops? I spelled manager right, but I did not capitalize as I didn't know I was supposed to.  Sorry about that. 

Take care.

**Comment by alexfornuto** [comment]
@marrie I already merged your fix and capitalized it. Thanks again!

**Pull request merged**
