### PR TITLE
How to install odoo 9 erp on cent os 7 1

### PR DESCRIPTION
**Pull request by damasosanoja**
First draft

### CODE REVIEW

**Comment by damasosanoja** [comment]
Second draft of this guide includes several editions made by @cwlinode in the Ubuntu version that applies to this one as well. Thanks for the input :+1:

**Comment by cwlinode** [comment]
Hi Damaso,

Thank you for pulling that in so quickly. I noticed that you have a 
second guide on the same topic for CentOS 7 too, PR #315. We 
unfortunately can not pay per-platform for the same guide. I'd like to 
encourage you to either make a multi-platform Odoo ERP guide, or to 
choose a single distro you would like the guide to work with.

I will wait until I hear further from you before pushing your 
Odoo/Ubuntu guide on to the copy edit phase.

Regards,

On 10/20/15 10:23 PM, Damaso Sanoja wrote:
>
> Second draft of this guide includes several editions made by @cwlinode 
> <https://github.com/cwlinode> in the Ubuntu version that applies to 
> this one as well. Thanks for the input :+1:
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/linode/docs/pull/315#issuecomment-149761023>.
>


-- 
Chris Walsh
Linode Guides & Tutorials

**Comment by damasosanoja** [comment]
No problem I understand your point. I was concerned about word count (around 1500 each guide). Lets keep the older one (Odoo/Ubuntu), i think will be more useful because most Odoo deployments are Ubuntu's.

**Comment by cwlinode** [comment]
Thank you, Damaso.

What you wrote was exemplary of what any impressive guide should be, so 
don't worry about word count. I moved your Odoo/Ubuntu guide on to copy 
edit.

Regards.

**Comment by damasosanoja** [comment]
Thanks, you are very kind. :smile:

**Pull request closed without merging**
