### PR TITLE
Own your cloud with nextcloud READY FOR TR 11/.13.17

### PR DESCRIPTION
**Pull request by Darkstar90**
Completed guide on NextCloud for CentOS 7. NOTE TO TECH REVIEWER:

Please send me a message if you encounter issues with NextCloud reporting PHP modules not found/installed and thus not working with Apache. Thanks.

### CODE REVIEW

**Comment by kcraig34** [comment]
@Darkstar90 -- Thanks for this guide, Andrew. The team is a bit inundated with other bounty submissions and a switch to a new content generator (Hugo), so we may not be able to address this guide immediately. But it is a priority and has been bumped up the queue. Thanks for your patience.

**Comment by kcraig34** [comment]
Andrew -

Could you please resubmit this PR by rebasing. Seems to be the easiest way for the team to get started on your commits.
Thanks, @Darkstar90!

Keith

**Comment by Darkstar90** [comment]
Hey Keith -

I have to admit, I had never used Git before I started working with your team, so I'm still learning how to use it properly. With that said, I've never heard of rebasing before, so I hope you guys can forgive me if I mess this up. I gave it a shot and everything seemed to complete correctly on my end, but I'm not sure if this produced the results you wanted. Please let me know if I need to give it another shot, and what I should be looking for to make sure it was done correctly. Thanks!

-Andrew L

**Comment by Guaris** [comment]
I'll handle it from here @Darkstar90, no worries.

**Comment by Guaris** [comment]
@Darkstar90 I've sent you an e-mail. When you see it, please respond.

**Comment by Darkstar90** [comment]
Hey Guaris, I sent along this guide to you via email and closed this PR. Let me know if you need anything else from me.

**Pull request closed without merging**
