### PR TITLE
[New] How to Install LAMP Stack on Fedora, AlmaLinux, or Rocky Linux

### PR DESCRIPTION
**Pull request by JeffreyNovotny**

### CODE REVIEW

**Comment by ash3T** [comment]
> 

Hi, Sorry, I don't know how can I connect you through other ways. I followed your guide on linode docs to install peertube. Thanks for writing that document. 

I got stuck in connect Peertube to Wasabi storage(use Cloudflare CDN). Can you write a doc on this please?

**Comment by JeffreyNovotny** [comment]
> 

Hi, thanks for the comment. I typically develop guides in consultation with the staff at Linode. They tend to know what their customers are looking for. I can mention to them that you're interested in this.

**Comment by ash3T** [comment]
Great. Thanks a lot. I have searched for connect Wasabi with Peertube. But
I cannot find any detailed instructions on this.

**Comment by ash3T** [comment]
> _ No description provided. _

Hi, I installed peertube again use the [doc](https://www.linode.com/docs/guides/how-to-install-peertube/) you wrote, and here is the issue. Just want to share with you, in case you want to update some of the command:

after running:

```
sudo curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
sudo apt-get install nodejs -y
```


***

SCRIPT DEPRECATION WARNING                    

  
  This script, located at https://deb.nodesource.com/setup_X, used to
  install Node.js is deprecated now and will eventually be made inactive.

  Please visit the NodeSource distributions Github and follow the
  instructions to migrate your repo.
  https://github.com/nodesource/distributions

  The NodeSource Node.js Linux distributions GitHub repository contains
  information about which versions of Node.js and which Linux distributions
  are supported and how to install it.
  https://github.com/nodesource/distributions


                          SCRIPT DEPRECATION WARNING


****

Hope this helps.

**Review by wildmanonline — APPROVED** [review]

**Pull request merged**
