### PR TITLE
MariaDB Coexisting With MySQL

### PR DESCRIPTION
**Pull request by thetechstewart**
This is an import from a submission given to us via email. It has not yet been reviewed for technical accuracy or edited for for proper formatting. It's purpose here is to gauge interest from the community on this subject, and solicit independent review of the contents.

### CODE REVIEW

**Comment by thetechstewart** [comment]
Encountered an error while attempting to run mysql_install_db script:

root@databasetest:~# /opt/mariadb/scripts/mysql_install_db --no-defaults --basedir=. --datadir=/opt/mariadb-data

FATAL ERROR: Could not find my_print_defaults

The following directories were searched:

    ./bin
    ./extra

If you compiled from source, you need to run 'make install' to
copy the software into the correct location ready for operation.

If you are using a binary release, you must either be at the top
level of the extracted archive, or pass the --basedir option
pointing to that location.

The latest information about mysql_install_db is available at
https://mariadb.com/kb/en/installing-system-tables-mysql_install_db

Querying original author for more information.

**Comment by gbti** [comment]
Hi James, you are right. The correct line will be:

. /opt/mariadb/scripts/mysql_install_db --no-defaults --basedir=/opt/mariadb --datadir=/opt/mariadb-data

**Comment by thetechstewart** [comment]
@gbti:  I was able to get the script to work, however the final command to start the MariaDB daemon fails with the following error:

root@databasetest:/opt/mariadb-data# su mariadb -c './bin/mysqld_safe --defaults-file=/opt/mariadb-data/my.cnf --basedir=/opt/mariadb --datadir=/opt/mariadb-data --plugin-dir=/opt/mariadb/lib/plugin --user=mariadb --pid-file=/opt/mariadb-data/mariadbd.pid --language=/opt/mariadb/share/english --socket=/opt/mariadb-data/mariadb.sock --port=3310'
sh: 1: ./bin/mysqld_safe: not found

**Comment by thetechstewart** [comment]
@gbti:  Just reaching out for an update on this guide.  Have you been able to look into the error that was noted in my last comment?

**Comment by alexfornuto** [comment]
Closing this for inactivity. @gbti please let us know if you would like to continue working on this, we can always reopen the PR.

**Pull request closed without merging**
