### PR TITLE
Add "Installing a Minecraft Server inside a FreeBSD Container"

### PR DESCRIPTION
**Pull request by RainbowHackerHorse**

### CODE REVIEW

**Comment by GuessWhoSamFoo** [comment]
Can you rebase? The directory structure has changed significantly since the team moved from Middleman to Hugo. Additionally the callout syntax (now called shortcodes) needs to be updated.

**Comment by RainbowHackerHorse** [comment]
Er, I can rebase, but I have no clue about hugo (or what you mean by callout syntax.) Only ever wrote one doc before, and that was back when I worked for the company (and had a friend in docs help me edit it >.> )
Any helpful links so I can make it conform?

**Comment by RainbowHackerHorse** [comment]
Also, as it's been changed to the correct directory location (last I checked) and only adding a single new file, what's the need for a rebase?

**Comment by GuessWhoSamFoo** [comment]
You're right - a rebase isn't really necessary atm (unless you're interested in writing more guide in the future). FreeBSD still isn't supported on a Linode yet but I can workaround with a VM.

**Comment by kcraig34** [comment]
@RainbowHackerHorse -- Thanks for re-submitting (and reminding us of) your FreeBSD guide. Eventually, Linode will adopt FreeBSD as a distro. Til then @GuessWhoSamFoo is a wizard in making things work.
If you want compensation, let me know. It'd be based on the guide's word amount. You'd then need to forward a W9 form and an invoice to Linode's payables team.

**Comment by GuessWhoSamFoo** [comment]
[Linode Copy of Minecraft?](https://trello.com/c/aXDvh2CP/167-linode-copy-of-minecraft)

**Comment by kcraig34** [comment]
@GuessWhoSamFoo -- Not following your question above. What about Linode copy of Minecraft?

**Comment by RainbowHackerHorse** [comment]
@GuessWhoSamFoo Yeah, I normally rebase right before I start working on one.
Since I've had this guide in my pocket since 2015, and had only written one other before, haven't needed to yet.
If I write another sometime soon, you bet I'll be rebasing :)
Also, while it's not outright supported on Linode yet, you can either follow my old guide:
https://www.linode.com/docs/tools-reference/custom-kernels-distros/install-freebsd-on-linode/
Or use my install image to play with it:
https://github.com/RainbowHackerHorse/FreeBSD-On-Linode
:D
Happy BSDing!

**Comment by GuessWhoSamFoo** [comment]
Closed in favor of 1292

**Pull request closed without merging**
