### PR TITLE
[New] Adds guide for installing Riot on Debian

### PR DESCRIPTION
**Pull request by danielsen**
Adds a guide for installing Riot on Debian

### CODE REVIEW

**Comment by nmelehan** [comment]
Deploy preview for *nostalgic-ptolemy-b01ab8* ready!

Built with commit ce48804f49e662712996d0fbcc82868d435284ea

https://deploy-preview-3391--nostalgic-ptolemy-b01ab8.netlify.app

**Comment by Rajakavitha1** [comment]
@danielsen  Thank you for the guide. I just validated the steps in the guide and I was getting a 403 error and the fix was to update /etc/nginx/sites-available/riot.demochat.com with root /var/www/html/riot.demochat.com/riot; 'riot' was missing. Please validate at your end and feel free to make the change if the fix works for you as well.

**Comment by danielsen** [comment]
@Rajakavitha1 Thanks for catching that. Confirmed it on my end and committed the correction.

**Comment by Rajakavitha1** [comment]
@danielsen !!! Thank you for making the changes. I also noticed that you will need matrix client installed if you need to use the matrix server. May be we need to mention this in the before you begin section.
Screenshot 2020-10-18 at 1 03 01 PM

**Comment by danielsen** [comment]
@Rajakavitha1 Good call. I added an item to the "Before You Begin" section with a link to the official client list.

**Comment by Rajakavitha1** [comment]
@danielsen could you please pull down the latest from the develop branch and then rebase the PR so that the deploy preview does not fail.

**Comment by leslitagordita** [comment]
closing in preference for: https://github.com/linode/docs/pull/3983

**Pull request closed without merging**
