### PR TITLE
Installing Roundcube on Ubuntu 14.04

### PR DESCRIPTION
**Pull request by seanthewebber**
New tutorial submission. Disregard commit email; real email address is swebber@yazzielabs.com.

### CODE REVIEW

**Comment by thetechstewart** [comment]
@seanthewebber Thanks for the submission.  I'll review this guide over the next few days and get back to you with any notes.

**Comment by seanthewebber** [comment]
@thetechstewart Any status updates?

**Comment by thetechstewart** [comment]
@seanthewebber: I've started working through the tech test on this article, however it seems that you've left out sections on correctly formatting the virtual hosts file to point to your Roundcube install location.  This information would need to be added, as the default configurations that you linked to from our library do not include the path where you are having the user install RoundCube.  If you can let me know once this edit has been made, I'll proceed with the tech test.

**Comment by alexfornuto** [comment]
@seanthewebber Please review the last email I sent you and adjust accordingly.

**Comment by seanthewebber** [comment]
@thetechstewart: I just made some changes to the document. Replacing /var/www/html/roundcube with /var/www/html/example.com/public_html/roundcube should make it jive with your LAMP stack tutorial and virtual hosts. Let me know if you encounter any other issues.

**Comment by thetechstewart** [comment]
@seanthewebber - Thanks for addressing those first issues that came up.  I've started running through another tech test, but it seems that the defaults installed by our LAMP server guide come up a bit short.  The following third party libs are flagged when attempting to start the web based portion of the Roundcube installation.

Auth_SASL:  NOT OK(Failed to load class Auth_SASL from pear.php.net)
Net_SMTP:  NOT OK(Failed to load class Net_SMTP from pear.php.net; See http://pear.php.net/package/Net_SMTP)
Net_IDNA2:  NOT OK(Failed to load class Net_IDNA2 from pear.php.net; See http://pear.php.net/package/Net_IDNA2)
Mail_mime:  NOT OK(Failed to load class Mail_mime from pear.php.net; See http://pear.php.net/package/Mail_mime)
Mail_mimeDecode:  NOT OK(Failed to load class Mail_mimeDecode from pear.php.net; See http://pear.php.net/package/Mail_mimeDecode)

Could you add in steps for installing or configuring any additional packages required to meet those dependencies?

**Comment by thetechstewart** [comment]
Closing pull request.

**Pull request closed without merging**
