### PR TITLE
Googledrive -- Try 3

### PR DESCRIPTION
**Pull request by scottinthebooth**
Trying again to merge the final into master branch

### CODE REVIEW

**Comment by ellekrout** [comment]
Yes! Perfect! Thank you!

**Comment by scottinthebooth** [comment]
YAY!  Awesome.  I heard from James, I'll be writing a guide on installation
and usage of MySQL Workbench next.  Loving this writing program!

Scott

**Comment by ellekrout** [comment]
I saw! We're ecstatic that you keep coming back to write for us. We really enjoy your guides, and like working with you! :)

I'm looking forward to the MySQL Workbench guide! I've been making a point to play with more MySQL outside of work, so it should be a fun read (and edit) for me.

**Comment by scottinthebooth** [comment]
Cool!  If there's a topic you'd like me to write on please let me know as
well!  I do a lot of general Linux stuff but unfortunately I don't have any
experience with the current topics on https://www.linode.com/docs/contribute
.

I could do a whole series on learning to program in Python though...

Scott

**Comment by ellekrout** [comment]
Hello again! Your article is officially live at https://linode.com/docs/applications/cloud-storage/access-google-drive-linode.

Our billing department has been forwarded your info and you should receive payment within 24 hours. Thank again for the submission! We'll get reviewing your MySQL Workbench guide as soon as we can! :D

**Pull request merged**
