### PR TITLE
Tiny Tiny RSS Installation Guide for CentOS 7

### PR DESCRIPTION
**Pull request by tylerjl**
This guide builds directly atop the [CentOS 7 LAMP](https://www.linode.com/docs/websites/lamp/lamp-on-centos-7/) guide (and the security guide) to walk through the installation and configuration steps for [Tiny Tiny RSS](http://tt-rss.org/). I've tested the guide on a dummy Vagrant box and the steps I've outlined seem to work without issues, even with SELinux installed (I know, I was surprised too).

I based this guide off of the other accepted guides I've submitted ([Terraria](https://www.linode.com/docs/applications/game-servers/host-a-terraria-server-on-your-linode) and the [ELK Stack](https://www.linode.com/docs/databases/elasticsearch/visualizing-apache-webserver-logs-in-the-elk-stack-on-debian-8)), so I think I've got most of the formatting/style down, though I'm happy to revise as needed. This seemed like a good fit since there aren't any self-hosted RSS guides currently in the Linode docs compendium, and some _other_ VPS providers have guides that are broken or otherwise outdated.

### CODE REVIEW

**Comment by brewn** [comment]
Hi @tylerjl 

Thanks for your submission! I've made a PR with my suggested changes here:

https://github.com/tylerjl/linode-docs/pull/6

If this looks good, please merge it and we'll move forward with getting this published.

**Comment by tylerjl** [comment]
Reviewed and merged the PR, thanks for the edit!

**Comment by brewn** [comment]
@tylerjl 

This guide has been published:

https://www.linode.com/docs/websites/apache/host-your-own-rss-reader-with-tiny-tiny-rss-on-centos-7

Could you email nbrewer@linode.com with your PayPal information?

Thanks!

**Comment by tylerjl** [comment]
Great! Thanks so much for helping it across the finish line. Better late than never 😄

**Pull request merged**
