### PR TITLE
Update configure-spf-and-dkim-in-postfix-on-debian-8.md

### PR DESCRIPTION
**Pull request by p4squ4l3**
Postfix ≥ 2.6 milter_protocol = 6, Postfix ≤ 2.5 milter_protocol = 2

### CODE REVIEW

**Comment by alexfornuto** [comment]
@tknarr or @p4squ4l3, would either of you care to elaborate on this change?

**Comment by tknarr** [comment]
The version numbers noted are the default versions (Postfix 2.6 changed the default from protocol version 2 to 6), and either protocol version works correctly so the change should be fine.

**Comment by p4squ4l3** [comment]
Yes, I read and tested
http://www.postfix.org/MILTER_README.html
http://www.postfix.org/postconf.5.html#milter_protocol

**Comment by alexfornuto** [comment]
Thanks @p4squ4l3, and @tknarr for reviewing.

**Pull request merged**
