### PR TITLE
Debian 8 Jessie + Nginx & StartSSL

### PR DESCRIPTION
**Pull request by capecodrailfan**
Updates the Debian 7 Wheezy guide on installing the latest version of
Nginx and deploying a StartSSL certificate for Debian 8 Jessie.

### CODE REVIEW

**Comment by thetechstewart** [comment]
@capecodrailfan:  This article has been assigned to a member of the Linode Technical Writing team for tech testing.  Once this process has completed, we will reach out to you with the next steps.

**Comment by alexfornuto** [comment]
Copy edit: https://github.com/capecodrailfan/docs/pull/1

**Comment by capecodrailfan** [comment]
Copy edit has been merged.

**Comment by alexfornuto** [comment]
Great! I just need to confirm your PayPal information (I sent you another email), and then we can publish!

**Comment by alexfornuto** [comment]
Thanks for your patience! We're publishing this guide now, and your payment is on its way.

**Pull request merged**
