### PR TITLE
[Update] Using the Linode Graphical Shell (Glish)

### PR DESCRIPTION
**Pull request by isgy**
the **Remote Access** tab no longer exists

### CODE REVIEW

**Comment by nmelehan** [comment]
Deploy preview for *nostalgic-ptolemy-b01ab8* ready!

Built with commit b6b6074154e590fd85534b4dfc3f5ef5d09fa6b5

https://deploy-preview-2855--nostalgic-ptolemy-b01ab8.netlify.com

**Comment by Rajakavitha1** [comment]
Hi @isgy !!!! Congratulations on your first PR to Linode Docs!!!! Thanks for the PR. Linode appreciates your contributions in making the docs better. We look forward to many more such valuable PRs.

**Comment by nmelehan** [comment]
hey @Rajakavitha1, I think for this we should make a new, separate cloud manager version with classic_manager_link and cloud_manager_link to link between them. The new version should have an updated screenshot of Glish. I'll hold off on merging this for now

**Comment by Rajakavitha1** [comment]
> hey @Rajakavitha1, I think for this we should make a new, separate cloud manager version with classic_manager_link and cloud_manager_link to link between them. The new version should have an updated screenshot of Glish. I'll hold off on merging this for now

Thanks @nmelehan !!! I completely forgot about the process for cloud_manager update process. I will submit a PR soon on that.

**Comment by Rajakavitha1** [comment]
This is now addressed in https://github.com/linode/docs/pull/2936.
Hence closing this PR.

**Pull request closed without merging**
