### PR TITLE
Black Mesa Dedicated Server on Debian and Ubuntu

### PR DESCRIPTION
**Pull request by davidebeatrici**

### CODE REVIEW

**Comment by thetechstewart** [comment]
@davidebeatrici - I've started the tech test on your guide, and thus far it does seem to be going smoothly.  I really appreciate the amount of detail that you've provided on configuring game modes and custom maps/map rotations!  I'll have to test client connectivity over the next day or so, once I have access to a computer with a copy of the game installed.  I'll try to wrap that up in the next day or two so we can move your guide on to the copy edit process.

**Comment by davidebeatrici** [comment]
Thank you very much for your feedback!
I will wait patiently for your client test result :smile:

**Comment by alexfornuto** [comment]
Head up: this branch is a great candidate for [squashing](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html)

**Comment by davidebeatrici** [comment]
Hello, I followed the linked tutorial: I downloaded my repository using "git clone", but when I use "git rebase -i HEAD~n" (where n is the number of commits to squash), it displays the commits of the master branch.
Could you help me, please?

**Comment by cwlinode** [comment]
@davidebeatrici I've moved your guide on to our copy edit phase.

**Comment by cwlinode** [comment]
@davidebeatrici Thank you for your contribution. Your guide has been published:
https://www.linode.com/docs/applications/game-servers/install-black-mesa-on-debian-or-ubuntu

Please confirm your Paypal email address with contribute@linode.com.

**Comment by cwlinode** [comment]
@davidebeatrici We've not yet heard anything from you and we'd like to get you paid for this guide. Please confirm your Paypal address with contribute@linode.com.

**Comment by davidebeatrici** [comment]
Hello,
I apologize for the delay, but currently I don't have PayPal, which is not for minors. I did some research and there's a "PayPal Students Account", but the instructions to get it are not clear.
I asked my friend for his PayPal address and sent you an email with it.
Sincerely,
Davide

**Pull request merged**
