### PR TITLE
Added rule to redirect all http traffic to https

### PR DESCRIPTION
**Pull request by gopalraha**
This rule will redirect the all http traffic to https using Apache rewrite rule.

### CODE REVIEW

**Comment by nmelehan** [comment]
Deploy preview for *nostalgic-ptolemy-b01ab8* ready!

Built with commit 6eee3980e0a79ab70d849be3c74490860314329a

https://deploy-preview-2805--nostalgic-ptolemy-b01ab8.netlify.com

**Comment by nmelehan** [comment]
Deploy preview for *nostalgic-ptolemy-b01ab8* ready!

Built with commit 408ea35f5e55e785fe841f2ce79d431456ae54c6

https://deploy-preview-2805--nostalgic-ptolemy-b01ab8.netlify.com

**Comment by Rajakavitha1** [comment]
Thank you for the PR @gopalraha !!!!
We look forward to many such valuable contributions from you.

**Comment by bagasme** [comment]
@gopalraha Your edits looks like using rewrite rules.

You can also try using `Redirect` directive to return `301 Redirect` to HTTPS site:

```apache
<VirtualHost *:80>
    ...
    Redirect 301 / https://yourdomain.tld
</VirtualHost>

<VirtualHost *:443>
    ServerName yourdomain.tld
    ....
</VirtualHost>
```

**Comment by wildmanonline** [comment]
@gopalraha Appreciate the PR. I was able to make the changes suggested by @bagasme and we should get this into a release very soon.

**Review by wildmanonline — APPROVED** [review]

**Review by nmelehan — APPROVED** [review]

**Pull request merged**
