### PR TITLE
First draft of Google Drive on Linode

### PR DESCRIPTION
**Pull request by scottinthebooth**

### CODE REVIEW

**Comment by ellekrout** [comment]
Hey! Before I go any farther in testing this, there is no longer an "Installed Application" option when creating credentials. Any suggestions?

**Comment by scottinthebooth** [comment]
aaannnddd Google changed its interface...

- Click "Credentials" in the left side menu
- Click the blue "Add Credentials" button in the middle of the screen
- Select Oauth 2.0 from the dropdown
- Click "Configure Oauth Consent Screen"
- Add a product name
- Save the consent screen
- Select Application Type "Other"
- Click "Create"

Google will give you the Client ID and Client Secret

That should get you going through the rest of the guide.  I'll update it to
reflect the new changes

Scott

**Comment by ellekrout** [comment]
Thanks for the prompt reply! I'm going to finish going through this now. :)

**Comment by ellekrout** [comment]
Hey Scott! Everything is working well. I've created a PR against your branch with some formatting fixes, and moved the files to the proper directories. Once you accept and then update with the fix you have above, we can move this on for a copy edit.

Thank you for coming back and submitting with us again! :smile_cat:

**Comment by scottinthebooth** [comment]
OK, I've revised the guide and added new screenshots.  I attached them to the comments as I couldn't figure out how to convince Git to add them to the repository.  I've been using Linux for years but Git is new to me...  Hopefully my pull request comes through OK

**Pull request closed without merging**
