### PR TITLE
Update theme reference

### PR DESCRIPTION
**Pull request by leslitagordita**
Includes:
- Improve product titles in search results
- Add excerpts to search results
- Truncate search result excerpts to 3 lines
- Improve sanitization of search input text
- Use locally-hosted web fonts
- Run Cypress tests on every pull request
- Sort product docs alphabetically on home page carousel
- API: Add anchor links to level 3 headings
- Block Disqus script for users who have opted out of functional cookies
- Fix visual collision between GitHub button and "Resources" tab on product doc pages on smaller desktops
- Apply CSS to stack share dropdowns before tabs on smaller desktops when the explorer is open
- Implement inline search field in power user mode
- Fix issue where closing the search would take you out of the "poweruser" mode
- Fix top results page displaying nothing when clicked from breadcrumbs
- Update partials ref: Update feature in community drop-down

### CODE REVIEW

**Comment by nmelehan** [comment]
Deploy preview for *nostalgic-ptolemy-b01ab8* ready!

Built with commit 0677d1c15673739b40ad2cbdb5b08687aa9913da

https://deploy-preview-4186--nostalgic-ptolemy-b01ab8.netlify.app

**Review by wildmanonline — CHANGES_REQUESTED** [review]
There's an issue with the changes made to fix the visual collision between the GitHub/StackShare dropdowns and the product tabs. The GitHub dropdown items are not visible on smaller desktops when the explorer is open.

As an aside, here are the items I didn't test (mostly because I wasn't able to or I wasn't finding them):
- Run Cypress tests on every pull request
- Block Disqus script for users who have opted out of functional cookies
- Implement inline search field in power user mode
- Fix issue where closing the search would take you out of the "poweruser" mode
- Fix top results page displaying nothing when clicked from breadcrumbs

**Comment by alertmybanjos** [comment]
@wildmanonline yes, the Github/Sharing links behave the same way on production (they disappear on mobile layout), so that's not caused by this PR... we need to open a separate issue to address that. Thank you for the reminder!

* Run Cypress tests on every pull request
* Block Disqus script for users who have opted out of functional cookies

Those are pretty well tested, I'm pretty confident we can proceed without additional validation.

* Implement inline search field in power user mode
* Fix issue where closing the search would take you out of the "poweruser" mode

These are directly related. Power user mode is what we call the alternate header when you scroll down the page. After scrolling down, click on the search icon (compare behavior on live site to behavior in develop). In the new branch, you should see the search box take the place of the breadcrumbs, whereas on the live site, you'll see the search box added below, increasing the total height of the header.

* Fix top results page displaying nothing when clicked from breadcrumbs

If you do a search, copy the url, paste it into a new tab, you should see breadcrumbs that say "Docs Home > Top Search Results"... if you click on that "Top Search Results" breadcrumb in production, you get a blank page. On development branch, you should still see the results listed.



The

**Comment by leslitagordita** [comment]
@wildmanonline I updated the theme reference to bring in @alertmybanjos changes.

**Review by wildmanonline — APPROVED** [review]

**Pull request merged**
