### PR TITLE
SSH Hardening Guide proposal

### PR DESCRIPTION
**Pull request by damasosanoja**
Hi everybody,

Being security a trending topic these days, i would like to know if there is interest in a "SSH Hardening Guide", a kind of mix between best practices, new security points to be addressed and also "old" tools that worth to be remembered.

A brief summary that comes to my mind is:

**SSH configuration hardening:**

- Access control directives.
- Protocol check.
- Idle timeout interval.
- Warning banners (legal stuff is often forgotten).
- Chroot strategies.
- Diffie-Hellman Algorithm configuration strengthen.
- Rhosts and host based authentication.

**SSH client-server hardening:**

- Key pair authentication strengthening.
- Port Knocking technique as additional security layer.

Best regards, waiting your comments.

### CODE REVIEW

**Comment by huw** [comment]
Seems sensible. I was considering writing a guide on SSH agent forwarding (for deploying to GitHub, for example) but found an article that [explained why it was insecure](https://heipei.github.io/2015/02/26/SSH-Agent-Forwarding-considered-harmful/). Perhaps a small part of this guide could include a way, if any, to harden agent forwarding?

**Comment by damasosanoja** [comment]
would be great to include something about forward agent :) 
although it is convenient to clarify that the article says that forward agent becomes insecure **if** host A is compromised ... that's a big "if", not to mention that any connection to that host is _by definition_ a security risk no matter the method you use.

**Comment by alexfornuto** [comment]
This sounds like a great main topic idea, and it sounds like you've listed enough sections that, when properly flushed out, will make for a great doc! 

But, just to stir the pot a bit, I wonder if I could get @akerl to comment on the last suggested topic, port knocking. I seem to recall several debates about whether it actually adds security or not.

Either way, please go ahead and write this guide. I look forward to reading it!

**Comment by damasosanoja** [comment]
Awesome, thanks for the feedback, will work on it.

**Comment by akerl** [comment]
<3

So, "port knocking", where you have firewall rules or similar and hitting the right ports in sequence is the magic, is pretty easy to bypass and not really a security bonus.

Comparatively, something where the contents of the request are the magic, and they cannot be replayed/spoofed, *do* add security:

* https://www.cipherdyne.org/fwknop/
* https://moxie.org/software/knockknock/

Both work by submitting cryptographically signed/encrypted requests for port opening. They can't be replayed or duplicated.

I'm personally a fan of fwknop since it uses standard gpg tooling for its crypto, but Moxie makes some good points about knockknock's simpler implementation being more provably secure.

**Comment by alexfornuto** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;47zrI5V3&#x2F;99-ssh-hardening"> SSH Hardening</a>

**Comment by alexfornuto** [comment]
Thanks for the input @akerl. I'm inclined to agree with you.

@damasosanoja feel free to write about either option, or a brief abstract on cryptographic port knocking, or to not include anything on the topic if you're not comfortable with it.

In the later case, maybe @akerl will lend his knowledge to the guide once it's published.

**Comment by damasosanoja** [comment]
Thanks for the input @akerl will work on it, now it's far more interesting topic ;)

**Comment by alexfornuto** [comment]
Great! Give us a buzz when this article is ready for review.

**Comment by alexfornuto** [comment]
I'm going to close this PR due to inactivity. @damasosanoja tag me when you're ready and I'll reopen it.

**Comment by damasosanoja** [comment]
Hi Alex,
I apologize for not answering earlier. I honestly did not see your answer nearly a month ago, as your team were working on the backlog I was not paying as much attention as before :)
I would love to continue this article if that's okay with you.

**Comment by alexfornuto** [comment]
Sounds good @damasosanoja, I suggest you start by filling out the introduction, and the section headers for us to review.

**Comment by damasosanoja** [comment]
Closing it now due to my human error is now #583

**Pull request closed without merging**
