### PR TITLE
[New] Install WordPress in LXD containers

### PR DESCRIPTION
**Pull request by simos**
This guide show how to setup WordPress in LXD system containers.
It builds on the previous guides about using LXD containers, and setting up a reverse proxy as a TLS Termination Proxy. 

Specifically, 

1. Shows how to setup the database container that WordPress requires. 
2. Shows how to install and setup WordPress on both Apache2 and NGINX web servers. 
3. Deals with TLS Termination Proxy issues. 

At the end of the guide, a user will be able to create many installations of WordPress on a server, and each installation will be isolated in its own system container.

### CODE REVIEW

**Comment by nmelehan** [comment]
Deploy preview for *nostalgic-ptolemy-b01ab8* ready!

Built with commit 37f88e4aae25b2b8c5e1e231d58f23f92a04cbd2

https://deploy-preview-3403--nostalgic-ptolemy-b01ab8.netlify.app

**Comment by simos** [comment]
Apply first the PR https://github.com/linode/docs/pull/3382
This tutorial depends on that above change in order to be as simple as possible.

**Comment by simos** [comment]
@nmelehan Is there anything else that I need to do from my part?

**Comment by simos** [comment]
@nmelehan I just saw that the tutorial went live!
https://www.linode.com/docs/guides/how-to-set-up-multiple-wordpress-sites-with-lxd-containers/

Does this mean you can close this PR?

**Comment by nmelehan** [comment]
Hi @simos - sorry about the delay here! We indeed finished up editing and publishing the guide, and I've sent over a separate email to you about invoicing for it. I'll go ahead and close this PR, but feel free to send any followup questions you have over to the email thread.

**Pull request closed without merging**
