### PR TITLE
[NEW] HL2DM Guide

### PR DESCRIPTION
**Pull request by Guaris**
Guide complete. Had to snip the extra section. Could not get the addons to install onto the HL2 server. Consider adding extra section snippet to More Information section during copy edit.

### CODE REVIEW

**Comment by davidebeatrici** [comment]
Thank you for the guide review.
For some reason GitHub doesn't show me the diff between my commit and yours.

Could you explain me why you didn't get the addons to install, please?

**Comment by Guaris** [comment]
@davidebeatrici Hey David--When I was editing your guide I spent a lot of time trying to make the extra section work, and every time, even on two different boxes, installing the extra section did not work. The server would not acknowledge that the add ons were installed. In the interest of time, I decided to cut the section because the HL2DM server works without it.

**Comment by davidebeatrici** [comment]
Hi, Guaris!

Very happy to meet another HL2DM player!
Even in 2017, after almost 13 years from its release, this is still one of the best multiplayer games ever made. Sadly Valve abandoned its development to entirely focus on Counter-Strike and Team Fortress, leaving it with some problems, but the work of the big community helped a lot to maintain a solid player base through the years.

Regarding the extra section: yes, the server works without it, but it would've been a great addition to the guide, as a vanilla server doesn't have an administration or bots system.

I executed every command on the server and checked if it worked before writing it in the guide.
Can you check if in `.steam/SteamApps/common/Half-Life 2 Deathmatch Dedicated Server/hl2mp/addons` you have the files **metamod.vdf** and **botrix.vdf**?

**Comment by davidebeatrici** [comment]
I have tried to install the server from scratch following the guide, everything works as expected.

The only problem I found is that an unneeded file is extracted:
```
  inflating: hl2mp/cfg/botrix.cfg    
caution: excluded filename not matched:  botrix.cfg
```

**botrix.cfg** is a configuration file for the game client that binds specific keys to Botrix commands, it's useful when creating waypoints for maps.

It can be fixed by replacing the command
```
unzip "/tmp/botrix.zip" -d "hl2mp/" -x "botrix-*" "botrix.cfg" "__MACOSX/*" "*.DS_Store" "*.dylib" "*.dll"
```
with
```
unzip "/tmp/botrix.zip" -d "hl2mp/" -x "botrix-*" "*.cfg" "__MACOSX/*" "*.DS_Store" "*.dylib" "*.dll"
```

**Comment by kcraig34** [comment]
@EdwardAngert -- Can you do an SEO edit? If so, pull in that card to Ready with this PR. If you can't, assign that card to me. You can also pull into Ready a graphics card so Rob can begin to create an image for guide.
Thanks.

**Pull request merged**
